### ISSUE TITLE
Responsive breakpoints are not consistent with "officials" breakpoints

### ISSUE THREAD

**Issue by adogor** [BuilderIO/builder#1027]
**Describe the bug**
For some components, responsive breakpoints are not in sync with officials breakpoints. For instance in the file `https://github.com/BuilderIO/builder/blob/main/packages/react/src/blocks/Columns.tsx` the column will be stacked at 999px if we choose tablet. It should be 991px.

It causes weird problems between 991 and 999px.

There might be others files affected.

**To Reproduce**
Create a Column components and set up Column to stack on Tablet. When inspecting the css on the column component you can see the problematic media query .

**Expected behavior**
Builder.io responsive breakpoints should be : 
- Mobile: 0-639px
- Tablet: 640px-991px
- Desktop: 992px+

according to : https://forum.builder.io/t/builder-io-breakpoints/321

**Screenshots**
![image](https://user-images.githubusercontent.com/4809384/170238932-91464cd4-a6ee-48da-8024-7d6b2619b970.png)

**Additional context**
On React, not tested for other frameworks.

**Comment by charkour** [comment]
Can confirm, this happens with the native Builder column component.
