### ISSUE TITLE
List input updates not reflected in editor

### ISSUE THREAD

**Issue by MikeBLambert** [BuilderIO/builder#1098]
**Describe the bug**
When editing a component with a list, when a list item is deleted, the changes aren't reflected in the editor.

**To Reproduce**
1. Insert a component that has an input with type 'list'.
2. Add one or more items to the list.
3. Edit one of the items.
4. Delete one item.

**Expected behavior**
The items in the list, when logged, should reflect the state of the editor.

**Screenshots**
![gif reproducing described bug](https://cdn.zappy.app/e7914efc3264f80a970537ce143c597e.gif)

**Additional context**
Found when using a NextJS app with the `@builder.io/react` version v2.0.1.

**Comment by teleaziz** [comment]
Hi @MikeBLambert thanks for reporting, we sent a fix in the last editor release, please let us know if you're still running into this issue.
