### ISSUE TITLE
Nuxt 3 error SSR

### ISSUE THREAD

**Issue by snchl-hess** [BuilderIO/builder#1158]
**Describe the bug**
Vue SDK bug during Nuxt 3 SSR rendering.
Work fine on get content during `onMounted` lifecycle, but produce error in `useAsyncData`.

**To Reproduce**
1. Create Nuxt 3 project `npx nuxi init nuxt-app`
2. Add builder.io vue sdk `yarn add @builder.io/sdk-vue`
3. Get builder.io content in `app.vue`

**Expected behavior**
Possible Nuxt 3 with SSR Builder.io content ? Then how ?

**Screenshots**
app.vue `script`:
<img width="681" alt="Capture d’écran 2022-07-21 à 23 48 19" src="https://user-images.githubusercontent.com/95022945/180320956-59140644-515a-4a3b-87ce-081e9096804a.png">

Error :
<img width="1074" alt="Capture d’écran 2022-07-21 à 23 50 16" src="https://user-images.githubusercontent.com/95022945/180321147-63991188-cd52-45cc-98ec-36a1d00099ff.png">

**Comment by carlead** [comment]
Hi,

I'm really interesting about this issue resolving.

Thank you,

**Comment by quentinblachehessautomobile** [comment]
Hi,

Since Nuxt 3 is on stable version, if you have any solution about this request ?

Thanks a lot,

**Comment by ojvribeiro** [comment]
In Nuxt 3.2.2 I'm receiving this error by just installing `@builder.io/vue`:

![image](https://user-images.githubusercontent.com/8026741/220019106-16ef5652-a62d-4e73-aa64-3c8a63514623.png)

Error disapears by uninstalling it.

**Comment by samijaber** [comment]
@ojvribeiro this is a completely separate package:

- `@builder.io/vue` is our old Vue SDK: https://github.com/BuilderIO/builder/tree/main/packages/vue
- `@builder.io/sdk-vue` is our new Vue SDK (Beta): https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/vue

The old Vue SDK is incompatible with Vue 3, and the 2 SDKs should never be used together.

@snchl-hess The current version of our Nuxt 3 + Vue SDK example uses `asyncData` and works correctly: https://github.com/BuilderIO/builder/blob/7eb57b780e1b3d2718fb42ef83ea91bc281c37a5/examples/vue/nuxt-3-catchall/pages/%5B...app%5D.vue#L48

So I'm marking this as closed.

**Comment by ojvribeiro** [comment]
@samijaber Thanks for the clarification.

Could you guys kindly especify in the docs that the `@builder.io/vue` only works for Nuxt 2?

![image](https://user-images.githubusercontent.com/8026741/220430853-a490610c-3d3a-44dc-bb27-b8810a71ba83.png)

**Comment by samijaber** [comment]
@ojvribeiro thanks for pointing this out: the docs should be updated. Can you link me to the docs URL in this screenshot?

**Comment by ojvribeiro** [comment]
Of course: https://www.builder.io/c/docs/quickstart

**Comment by SurinderSing** [comment]
Unknown file extension ".css" for C:\Users\lenovo\Desktop\task-folder\nuxt-with-builerIo\node_modules\@builder.io\sdk-vue\vue3\lib\node\style.css

![image](https://github.com/BuilderIO/builder/assets/85671449/897a863d-2b7d-4092-9411-a4cd058c30cc)

facing this error on the current latest version of sdk - "@builder.io/sdk-vue": "^0.9.0", but it is working fine in version "@builder.io/sdk-vue": "^0.7.6"

@samijaber  can you help me how it will work correctly in the latest versions.

**Comment by samijaber** [comment]
@SurinderSing please see CHANGELOG https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/vue/CHANGELOG.md#080

**Comment by we-surinder-s001** [comment]
![image](https://github.com/BuilderIO/builder/assets/155720038/0235e8bd-afba-442b-88e6-65ea9a15e148)

@samijaber I have removed the css import still facing the same issue 
![image](https://github.com/BuilderIO/builder/assets/155720038/29f94909-f16e-47d3-92f2-ab1191b6e28e)

[Vue Router warn]: uncaught error during route navigation:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for D:\xampp8117\htdocs\surinder-s001\nuxt-practice-project\builder.io-practice\node_modules\@builder.io\sdk-vue\vue3\lib\node\style.css
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:141:22)
    at async ModuleLoader.load (node:internal/modules/esm/loader:409:7)
    at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:45) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

**Comment by samijaber** [comment]
Let's move the conversation to https://github.com/BuilderIO/builder/issues/2917.

**Comment by Rolanddoda** [comment]
> Could you guys kindly especify in the docs that the @builder.io/vue only works for Nuxt 2?

@samijaber builderIO ONLY works with Nuxt2?? 😯😯

**Comment by samijaber** [comment]
@Rolanddoda no, that comment is a year old. Builder works with Vue 3 and Nuxt 3

**Comment by Rolanddoda** [comment]
@samijaber thanks for the quick reply! 

But the website still says Nuxt 2!
![image](https://github.com/BuilderIO/builder/assets/18482346/2439e4fb-84ae-4b22-8cc8-65da8203c08c)


But if you say that it now works, that's great! I am trying so hard to convince the company to use Builder. If you happen to have any kind of resources related to Builder + Nuxt 3 then please share them with me. I would highly appreciate it.

**Comment by samijaber** [comment]
Ah, this is an outdated reference and should say Nuxt 3 (or just Nuxt). Thanks for pointing it out

**Comment by samijaber** [comment]
As for examples:

- https://github.com/BuilderIO/builder/tree/main/examples/vue/vue-3
- https://github.com/BuilderIO/builder/tree/main/examples/vue/nuxt-3-catchall
- https://github.com/BuilderIO/builder/tree/main/examples/vue/nuxt-3
