### ISSUE TITLE
Unable to add child block to built-in column block.

### ISSUE THREAD

**Issue by srhyne** [BuilderIO/builder#1164]
**Describe the bug**
I'm unable to add child blocks to the built in column block.

**To Reproduce**
1. On a blank page, insert Columns block
2. Click add block on first column and select text block.
3. Text block becomes sibling of Columns block below it.
4. Attempting to use Layers to force hierarchy does not work
5. Attempting to drag a block into either side of the column drop zones does not work. 

**Expected behavior**
I expected to be able to add child blocks to each side of the columns block. 

**Screenshots**

42 sec Vimeo video 👇 
https://vimeo.com/732810328/1292aaeb81

**Additional context**

Packages..

```
"nuxt-edge": "latest",
"@builder.io/sdk-vue": "dev",
```

**Comment by srhyne** [comment]
Thank you for prioritizing this @mhevery and @samijaber! Loving Builder.io

**Comment by samijaber** [comment]
@srhyne fixed in the latest `dev` version

**Comment by srhyne** [comment]
Thank you so much, @samijaber
