### ISSUE TITLE
Register Custom Box component places component in wrong section in Builder UI

### ISSUE THREAD

**Issue by charkour** [BuilderIO/builder#1166]
**Describe the bug**
When registering a customer React component called `Box`, it will show up in `Basics` rather than `Custom Components` in the Builder UI

**To Reproduce**
1. Use @builder.io/react SDK to register a custom Builder component
2. Push changes
3. View in connected Builder UI

**Expected behavior**
The custom Box component should appear in `Custom Components` section

**Screenshots**
![Screen Shot 2022-07-25 at 1 51 16 PM](https://user-images.githubusercontent.com/33156025/180842965-fbe70050-74a5-43d5-b2f3-06565593b294.png)

**Additional context**
I tried looking for documentation on how to override default components and I thought I had found some, but when I search again, I could not find the documentation. The doc search could be improved.

We also have registered a `Button` component, but it shows up in the `Custom Components` section in the Builder UI as expected.

Here is the code.

```tsx
const Box: React.FC<BuilderProps> = (props) => {
    // TODO: is there a better way to omit these
    const { attributes, builderBlock, builderState, ...rest } = props;
    return <div {...attributes} {...rest} />;
};

Builder.registerComponent(withChildren(Box), {
    name: 'Box',
    canHaveChildren: true,
    noWrap: true,
});
```

Thanks for the help!

**Comment by charkour** [comment]
Looking at the code, is it necessary to pass `builderBlock` and `builderState` to my Component with `noWrap` set to true?

**Comment by mhevery** [comment]
Hi @charkour ,

Yes, there are a set of names that are considered internal to Builder. `Box` is one of them. These names are hard-coded, and we allow you to register (overwrite) them so that you can have custom implementations. Ideally, this should have been namespace, but it is not, and namespacing it now would be a breaking change. So sadly this will not be fixed.

**Comment by charkour** [comment]
Gotcha, thanks for the explanation. 

When v2 eventually comes out, this would be nice to have them namescaped. Thank you.
