### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by charkour** [BuilderIO/builder#1167]
Hey Builder team,

My team is using the Builder React SDK in production and have noticed a number of issues with the React package specifically around the TS support.

Wanting to help out the Builder ecosystem as a whole, we would like to make changes and contribute to the repo. There is no CONTRIBUTING.md to help devs get started locally.

Can we consider adding contributing guidelines?

This question spawned because there is both a `package-lock.json` and `yarn.lock` present at the repo root. Which package manager is used for this project? Thanks.

**Comment by mhevery** [comment]
Thanks for reaching out!

1. Yes contributions are welcome. Would you like to take a stab at `CONTRIBUTING.md`
2. It is now `yarn` the `package-lock.json` should be deleted.

**Comment by charkour** [comment]
Hey @mhevery, 

Thank you for getting back to me and for answering my questions. I can get started on this once I get some free time in my work week. Thanks.

**Comment by charkour** [comment]
I will unassign myself. Am not planning on taking this on.

Thanks for understanding.
