### ISSUE TITLE
Images don't seem to work correctly in amp-mode.

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#117]
The `Image` component seems to be acting up when rendering page in `amp-mode`. 

Getting the following errors: 

![tg_image_2145281078](https://user-images.githubusercontent.com/2464556/77674510-0187c100-6f8c-11ea-806d-85423297ebd0.jpeg)

For debugging purposes you can have a look at the builder page id `350f24762e8d48c3adea91b5e753d8be` in our account. 

A live preview of this issue could be viewed here: https://hs.mersenne.now.sh/

**Comment by homanp** [comment]
Seems like the image tag is not rendered even though it's visible in the editor.

**Comment by homanp** [comment]
<img width="1606" alt="Screenshot 2020-03-26 at 18 21 34" src="https://user-images.githubusercontent.com/2464556/77676527-bf13b380-6f8e-11ea-8253-e264692b9c72.png">

Here is how it looks inside the editor.

**Comment by kevva** [comment]
@steve8708, this should probably reopened. Here's an example `img` tag:

```html
<img decoding="async" sizes="(max-width: 638px) 95vw, (max-width: 998px) 97vw,  54vw" src="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=966" srcset="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=966, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=606 606w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=966 966w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=749 749w" class="i-amphtml-fill-content i-amphtml-replaced-content">
```

The problem here seems to be the CDN which doesn't serve the images with the correct size even though the `width` parameter is set.

**Comment by steve8708** [comment]
Hey @kevva - which images look wrong to you? I'm clicking through the various links and seeing the right sizes (e.g. width=100 gives me a 100px wide image https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fda62cf9c04b04780b4cf5ee4103e8f85?width=100)

Note thought that width is considered a _max_ width. We won't increase an images size since that would lead to an unnecessarily large and pixelated image, so the only known time that the CDN will return a differently size image is if the link is if the width param is larger than the originally uploaded image's width

**Comment by kevva** [comment]
@steve8708, sorry, my mistake. I must've been something wrong with my eyes. However, the issue still remains and it looks like some of the images are missing  a width in their `srcset`, eg:

```html
<img decoding="async" sizes="(max-width: 638px) 95vw, (max-width: 998px) 97vw,  27vw" src="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966" srcset="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=100 100w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=200 200w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=400 400w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=800 800w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=1200 1200w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=1600 1600w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=2000 2000w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=606 606w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966 966w, https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=366 366w" class="i-amphtml-fill-content i-amphtml-replaced-content">
```

Notice that there is one image (https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966) that doesn't have a size. I can see it on multiple images, but not all for some reason.

![image](https://user-images.githubusercontent.com/709159/77939313-462a9980-72b7-11ea-927b-e3fffe94996e.png)

**Comment by steve8708** [comment]
Ah I see, maybe it doesn't like that the default URL is the same size as one of the generated URLs in srcset too - assigning to @teleaziz to investigate futher
