### ISSUE TITLE
@builder.io/sdk-react: NextJS: failure to load in SSR

### ISSUE THREAD

**Issue by charkour** [BuilderIO/builder#1217]
**Describe the bug**
When using the recently released Beta React SDK [@builder.io/sdk-react@0.0.1-1](https://www.npmjs.com/package/@builder.io/sdk-react/v/0.0.1-1) with Next.js and Next.js throws and error `Server Error SyntaxError: Cannot use import statement outside a module` when trying to server-side render the builder `RenderContent` component. 

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/33156025/185497342-d3fcaa8a-03d6-4dd7-9ec9-8ba96651d58c.png">

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/nextjs-wtbue6?file=pages/index.js)

**Expected behavior**
We can use the builder SDK with SSR (eventually we will want to use server component with the SDK)

**Additional context**
one workaround to is only render the Builder component on the client. 

Thanks for the help! I'm excited to see that the bundle size is only 13 kB. Seems more reasonable.

**Comment by charkour** [comment]
cc @samijaber. Thanks!

**Comment by samijaber** [comment]
Ah, we need to add `type: module` to the npm package. Will do that and test it out soon

**Comment by charkour** [comment]
Thanks! Will be happy to test and give feedback as newer versions are released.

**Comment by charkour** [comment]
Thanks @samijaber,

I just updated the [stackblitz](https://stackblitz.com/edit/nextjs-wtbue6?file=pages/index.js) and updated to v0.0.1-4 and the issue persists when attempting to SSR the builder content.

The version works when only doing CSR.

`Error: Cannot find module 'commerce/node_modules/@builder.io/sdk-react/src/context/builder.context' imported from commerce/node_modules/@builder.io/sdk-react/src/blocks/symbol/symbol.js`

![image](https://user-images.githubusercontent.com/33156025/186199397-527fc272-294e-4fb5-9d69-e7a240be2f55.png)

Hope this helps. Would you like me to make another issue or can we re-open this one? Thank you!

**Comment by charkour** [comment]
Thanks @samijaber, that's looking great!

Thanks for the quick fix.
