### ISSUE TITLE
Registering Custom Components on Next.js

### ISSUE THREAD

**Issue by buraksakalli** [BuilderIO/builder#1223]
**Describe the bug**
I followed the documentation for registering custom components on Next.js. I applied all requirements but can't see the component under the Custom Components section in the editor.

I created a new project with create-next-app, but the issue still exists.

I initialized an example next.js project with Builder.io. You check the custom component under `/components/Heading/Heading.tsx` on https://github.com/buraksakalli/builderio-registering-component.

**To Reproduce**
1. Follow the documentation for registering custom component implementation -> https://www.builder.io/c/docs/custom-components-setup
2. When you apply all the requirements in the document, you should see the component in the editor, but you won't.

**Expected behavior**
Components should be listed in the editor.

**Screenshots**
<img width="299" alt="Screen Shot 2022-08-23 at 9 50 24 PM" src="https://user-images.githubusercontent.com/10114716/186229442-bb9e374d-c717-4c3f-a4c9-31a74aef90a5.png">

**Comment by samijaber** [comment]
What commands are you running, and which content page are you trying to open?

I followed these steps:
- cloned your repo
- ran `yarn`
- put in an API key for a builder space of mine
- ran `yarn dev`
- opened the builder.io/content page for a page on `/`
- pointed the preview URL to `http://localhost:3000`

and I see
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/1393142/186235276-b0287904-af0a-4bc8-8a31-83c4f5ea5f9a.png">

**Comment by buraksakalli** [comment]
Hi @samijaber, thanks for the quick reply. 

I didn't know I had to point to the preview link to localhost.

But, I'd like to reach the custom component for a section or a page created on Builder.io.

**Comment by samijaber** [comment]
> I didn't know I had to point to the preview link to localhost.

I am only doing that to debug your codebase. In a normal scenario, you would deploy your app to a real server/website and set that as your default URL for your pages: https://www.builder.io/c/docs/guides/preview-url#model-url

> But, I'd like to reach the custom component for a section or a page created on Builder.io. Is it possible?

Not sure I follow the question, but yes this is entirely possible. Once you have a custom component you can use it in any section, page or symbol you want to create.

**Comment by buraksakalli** [comment]
Thanks for the explanation. @samijaber 

I have a section, and when I open it on Builder.io, I can't see the custom component. :/ I can only see it when I redirect the preview link to localhost. :/

**Comment by samijaber** [comment]
yes, if the preview link is a default one like `https://preview.builder.codes?model=page&previewing=true` then it will not point to your codebase/site. Therefore it has no idea what custom components you have.

You either have to:
- deploy your app to a real server/website, and point to that
- point to your localhost

**Comment by buraksakalli** [comment]
It's clear. Thanks for helping, @samijaber.
