### ISSUE TITLE
Angular Build failing because of wrong import from node.js

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#13]
During build process (`ng build`) in Angular (v8) I get an error:

`ERROR in /Users/x/workspace/x-frontend/node_modules/@builder.io/sdk/dist/index.umd.min.js
Module not found: Error: Can't resolve 'http' in '/Users/lyczos/workspace/x-frontend/node_modules/@builder.io/sdk/dist'
ERROR in /Users/x/workspace/x-frontend/node_modules/@builder.io/sdk/dist/index.umd.min.js
Module not found: Error: Can't resolve 'https' in '/Users/x/workspace/x-frontend/node_modules/@builder.io/sdk/dist'
`

To fix the issue I had to add 
```
"browser": {
    "./dist/index.umd.min.js":  "./dist/index.umd.min.js", 
    "http":  false, 
    "https":  false
  },
```
in `@builder.io/sdk` -> `package.json`.
`node_modules/@builder.io/sdk/package.json`

Same issue will appear for included example application

**Comment by steve8708** [comment]
ah yes, thanks for reporting @lyczos ! this has been an ongoing issue with having conditional dependencies for browser vs server and static bundlers wanting to force bundling all dependencies for all builds

I have recently found a solution for this, I'll add it to `@builder.io/sdk` now
