### ISSUE TITLE
sdk-vue: Incorrect column styling

### ISSUE THREAD

**Issue by canleon-cf** [BuilderIO/builder#1306]
**Describe the bug**
In every tested version of @builder.io/sdk-vue, the columns get displayed below each other, instead of in a row. This behavior was not the case in @builder.io/vue.

**To Reproduce**
1. Embed builder.io into your page with e.g. sdk-vue 0.0.2
2. Add a column

**Expected behavior**
The columns are below each other with an additional indent.

**Screenshots**
Columns in @builder.io/vue 0.1.12
<img width="1044" alt="Bildschirmfoto 2022-10-06 um 09 31 45" src="https://user-images.githubusercontent.com/115140589/194245308-9040e82e-9c4e-4c13-89b4-36ffcc23a4e0.png">
Columns in @builder.io/sdk-vue 0.0.2
<img width="1044" alt="Bildschirmfoto 2022-10-06 um 09 31 11" src="https://user-images.githubusercontent.com/115140589/194245387-46f7478d-af0e-42ce-90da-48b01acedd38.png">

**Additional context**
We are using vue2 and nuxtjs. The content is embedded like described in the [examples for vue2](https://github.com/BuilderIO/builder/tree/main/examples/vue/vue-2).

**Comment by samijaber** [comment]
Thanks for filing. We are investigating this.

**Comment by samijaber** [comment]
This has been fixed in version `0.0.3`

**Comment by samijaber** [comment]
Note that you now need to manually import the CSS styles of the SDK. See an example here: https://github.com/BuilderIO/builder/blob/8cf98abbf2801ed92a6aecf9165ee8ae39fc0c12/examples/vue/vue-3/src/App.vue#L2-L4
