### ISSUE TITLE
Customized breakpoints not working as expected

### ISSUE THREAD

**Issue by JRMaitre-Dandy** [BuilderIO/builder#1321]
**Describe the bug**
Customized breakpoints not working as expected

**To Reproduce**
I updated the breakpoints to match the ones we use in Material (mobile < 600 < tablet < 900 < desktop), After I did so in the account settings, I noticed 2 things didn't work as I expected:

1/ 
- I selected tablet size at the top of builder
![image](https://user-images.githubusercontent.com/111591346/197015423-53f1f0c9-09c2-48d0-b28c-e673fb578260.png)
- I manually set a css property to `flexDirection: column` on an element
- I noticed that the css was applied for mobile size instead of tablet (I checked that by looking at the component in JSON view and noticing these values)
```
"responsiveStyles": {
    "large": {
      "maxWidth": "1200px",
      "marginLeft": "auto",
      "marginRight": "auto"
    },
    "small": {
      "flexDirection": "column"
    }
  }
```

2/ The `Column` builder component attribute to switch from row to column at `tablet` size didn't honor the new value of my `tablet` breakpoint. So in the rendered markup I noticed that it was still applying the style at the old breakpoint's value (`991px` instead of the `900px` I expected.)
![image](https://user-images.githubusercontent.com/111591346/197014903-f6474cf6-7034-4c12-bf68-ee6e65d93782.png)

**Expected behavior**
1/ I would expect the custom CSS to be applied for the `medium` size when `tablet` is selected at the top, even with a custom breakpoint
2/ I would expect the `Column` component attribute to switch to column mode to take into account the customized breakpoint value.

#####
Hope this is clear enough, let me know if I can add more details. Thanks!

**Comment by samijaber** [comment]
@JRMaitre-Dandy Are you still experiencing this issue? I am closing this issue due to staleness, but please feel free to reopen if you still have problems with customized breakpoints
