### ISSUE TITLE
Saved filters view does not work with choosing to save for organization

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#135]
Hi @steve8708 

Seems like the saved filter views only works when you save to `Your Views` within the Builder content page `https://builder.io/content` . 

When saving the filters for `Your Organization` they disappear and are no where to be found.

**Comment by homanp** [comment]
Any updates on this issue?

**Comment by steve8708** [comment]
Hey @homanp - we actually fixed this just last week but have identified another issue related to organization views that we'll look into today

**Comment by homanp** [comment]
Thanks Steve!

**Comment by steve8708** [comment]
@homanp I actually am unable to reproduce that second issue we had thought had occurred, can you verify if this is working for you and if not what the behavior you see is?

**Comment by homanp** [comment]
@steve8708 seems to work just fine now. Will go ahead and close this issue. Thanks again!
