### ISSUE TITLE
Warning: Prop `data-timestamp` did not match

### ISSUE THREAD

**Issue by cj** [BuilderIO/builder#136]
Hi,

I just tried the nextjs example and it's giving me this error/warning in the console:

```
Warning: Prop `data-timestamp` did not match. Server: "1585795271556" Client: "1585795275202"
    in div
    in t (at pages/index.tsx:39)
    in div (at pages/index.tsx:37)
    in Home (at _app.tsx:35)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (at App/index.tsx:22)
    in App (at _app.tsx:34)
    in MyApp
    in Container (created by AppContainer)
    in AppContainer
```

"@builder.io/react": "^1.1.12"
"next": "^9.3.0"

Please let me know if you need anything else.

Cheers!

**Comment by steve8708** [comment]
Thanks for reporting @cj - went ahead and removed this timestamp param as it was just there for debugging purposes and rarely used, this error should be gone in `@builder.io/react@1.1.13-10`
