### ISSUE TITLE
Support for typescript and maybe Nextjs 9.3

### ISSUE THREAD

**Issue by kkshmz** [BuilderIO/builder#142]
Hi I want to address 2 things in this issue.

1. Is there a clear way of making this work with Typescript? I am using typescript 3.8 and find some errors. 
Builder Component currently gives errors in typescript, but am I missing some other typings that should be included with the builder package?
I would love to make examples also for typescript users, especially those using next.js

2.
Nextjs has changed a little bit of the data fetching schema into 2 parts with the introduction of the getStatic props, found [here](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)

Thanks.

**Comment by ca136** [comment]
Thanks for filing @kkshmz, do you mind sharing some more details on the TS errors you're seeing? Or even better, creating a codesandbox or plunker with a minimal reproducible example. That will help us diagnose and isolate the issues you're seeing.

**Comment by kevva** [comment]
@kkshmz, I added a PR with some updates for newest Next.js version https://github.com/BuilderIO/builder/pull/158.
