### ISSUE TITLE
Changing attributes e.g `aspect ratio` breaks images in amp-mode.

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#144]
Steps to reproduce: 

1) Create an AMP page inside the editor.
2) Add an image with desired ratio and other attributes.
3) Save page. 
4) Edit image attributes such as aspect ratio.

No images will be visible and the following error shows up in the console: 

```
Uncaught Error: The last option must not have a media condition​​​
    at Za.f.assert (log.js:429)
    at D (log.js:995)
    at new mi (size-list.js:167)
    at li (size-list.js:136)
    at HTMLElement.Di.b.applySizesAndMediaQuery (custom-element.js:680)
    at ci.f.applySizesAndMediaQuery (resource.js:374)
    at h (resources-impl.js:1173)
    at yj.setState (finite-state-machine.js:72)
    at Cj.f.doPass (resources-impl.js:743)
    at ji.Ug (resources-impl.js:134)
```

**Comment by steve8708** [comment]
Oh interesting, @teleaziz I think this may be per your latest update where you remove the duplicates (which removes the srcset url without the size aka "media condition")

**Comment by homanp** [comment]
@teleaziz any news on this? Still seeing broken images with the above error.

**Comment by mrkoreye** [comment]
@homanp Sorry it is still an issue for you!

I am trying to reproduce on my end and I am not able to. Can you provide any more context on how to reproduce the error?

I will let you know if I find and fix any other issues that might be causing or are related this one.

**Comment by homanp** [comment]
Hey! 

Well You can see the errors here https://hs.mersenne.now.sh/. All images Have that issue.

And We are experiencing it on other AMP pages as well. 

Is there anything else you need?

**Comment by homanp** [comment]
Just to clarify, this only happens on models with the type AMP and started appearing after your latest image fix.

**Comment by mrkoreye** [comment]
Thanks, that should help! I will let you know if I need anything else to investigate.

**Comment by homanp** [comment]
@mrkoreye so I figured out that this only happens in amp-mode when you put an image inside a box. Not otherwise.
