### ISSUE TITLE
Error when saving plugin

### ISSUE THREAD

**Issue by kevva** [BuilderIO/builder#145]
Upon adding and saving a plugin, I get the following error

![image](https://user-images.githubusercontent.com/709159/79855211-f11c0800-83ca-11ea-98a9-35ce364e4020.png)

![image](https://user-images.githubusercontent.com/709159/79854898-7a7f0a80-83ca-11ea-9e57-d917a423745a.png)

This is not related to any particular plugin since it happens with any plugin I try to install.

**Comment by mrkoreye** [comment]
@kevva thanks for letting us know! We ran into this issue earlier and are working on a fix. Hopefully we will be able to deploy the fix by the end of the week.

**Comment by kevva** [comment]
@mrkoreye, just tried installing a plugin again, and it seems to work now. Closing this.
