### ISSUE TITLE
Latest release breaks server side rendering

### ISSUE THREAD

**Issue by kevva** [BuilderIO/builder#151]
Due to this commit https://github.com/BuilderIO/builder/commit/e90f85846775e9eee61c58e4c96320f7dd06d607, server side rendering now fails with the following error:

```
ReferenceError: document is not defined
    at /.../node_modules/@builder.io/sdk/dist/index.cjs.js:2225:37
    at Object.<anonymous> (/.../node_modules/@builder.io/sdk/dist/index.cjs.js:2231:2)
```

**Comment by steve8708** [comment]
Thanks @kevva  - fixed and published with @builder.io/react@1.1.16-alpha.2
