### ISSUE TITLE
The default Image aspect ratio gives a strange container height in amp-mode

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#153]
Seems to be some kind of issue with the `builder-image-sizer`?

<img width="1792" alt="Screenshot 2020-04-28 at 14 22 26" src="https://user-images.githubusercontent.com/2464556/80486804-0c9f8980-895c-11ea-8e10-2e4098890e3c.png">
<img width="1792" alt="Screenshot 2020-04-28 at 13 43 15" src="https://user-images.githubusercontent.com/2464556/80486823-11fcd400-895c-11ea-9146-3419bbf1ee5e.png">

**Comment by steve8708** [comment]
Ah! We shouldn't use the sizer in amp mode - thanks for catching @homanp

**Comment by steve8708** [comment]
Updated in `@builder.io/react@1.1.16-alpha.7`
