### ISSUE TITLE
Cannot see added components in page

### ISSUE THREAD

**Issue by kevva** [BuilderIO/builder#157]
Since https://github.com/BuilderIO/builder/commit/8a910d7ce53c8e3b184a14d8f7661bab5e6cbfda, I'm unable to see components I add to *some* (not all) pages. I haven't narrowed down why, but downgrading fixed the issue.

![image](https://user-images.githubusercontent.com/709159/80962160-c9866000-8e0c-11ea-9e80-59c4cefcd64d.png)

![image](https://user-images.githubusercontent.com/709159/80962180-d440f500-8e0c-11ea-9ed5-d104e6f20d3b.png)

**Comment by steve8708** [comment]
Thanks for reporting @kevva - so we can dig deeper, can you share the contents of your package-lock.json file?

**Comment by kevva** [comment]
Sure, https://gist.github.com/kevva/75be2dedc594deca05bb228d0597d4a7.

**Comment by mrkoreye** [comment]
@kevva did you find out anything more while trying to investigate? Are there certain components that work, certain components that do not work? Have you noticed any similarities between pages that have this behavior and others that do not? I tried to reproduce locally, but was not able to run into the issue on my own.

**Comment by kevva** [comment]
I didn't find anything in particular regarding the pages. It seems to be pretty random because sometimes it works on a page, and sometimes it doesn't. I can edit components that already exist on the page as well, but not move them around. And this happens with all components, not only the text one. 

![image](https://user-images.githubusercontent.com/709159/81013080-e0ec3a00-8e5a-11ea-96e5-ce601f4ba09d.png)

**Comment by mrkoreye** [comment]
Hmm, okay. Can you link me to the content entry in Builder (i.e. builder.io/content/<id> )? I might be able to find something in there.

**Comment by kevva** [comment]
Sure, here you go https://builder.io/content/cfbe33a922164f319bf90eca3edc1647.

**Comment by kevva** [comment]
Unfortunately, I can still see this problem. To me it feels like some sort of race condition since I could make some pages work *sometimes*.

**Comment by kevva** [comment]
Unfortunately, I'm still seeing this issue.

**Comment by steve8708** [comment]
hey @kevva - did you try `@builder.io/react@1.1.16-alpha.12`?

**Comment by kevva** [comment]
Yes, I did.

**Comment by steve8708** [comment]
@kevva could you try `@builder.io/react@1.1.19-alpha.0`?

**Comment by kevva** [comment]
@steve8708, can confirm that it works fine now.
