### ISSUE TITLE
builderVisitorId cookie cannot be disabled when using RenderContent

### ISSUE THREAD

**Issue by n4bb12** [BuilderIO/builder#1606]
**Describe the bug**
It's not possible to disable tracking cookies using `RenderContent`.

**To Reproduce**
1. Set up your SDK as per https://www.builder.io/c/docs/integrating-builder-pages (for me, it's sdk-svelte but the SDK doesn't seem to matter)
2. Use `RenderContent` and disable tracking: `<RenderContent ... canTrack={false} />`

**Expected behavior**
No builder.io cookies should be set.

**Additional context**
I identified the problem to be this line:
https://github.com/BuilderIO/builder/blob/eb8c3135d34055d31cac4a6ef3b1dee9b32cd610/packages/sdks/src/components/render-content/render-content.lite.tsx#L111

The expression always evaluates to `true` regardless of the value of `props.canTrack` since `false || true` is `true`.

If the intention was to enable tracking by default, the code would have to be `props.canTrack !== false` for example, right?

Or if the intention was to convert it to a boolen, it would have to be `Boolean(props.canTrack)`  or `!!props.canTrack` or similar.

**Comment by mrkoreye** [comment]
@samijaber can you please investigate?

**Comment by samijaber** [comment]
@n4bb12 Thank you for being so thorough, this is probably the most helpful bug report I've received in a while!

**Comment by n4bb12** [comment]
Thanks!
