### ISSUE TITLE
Custom Javascript seems to only run on the client side.

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#169]
I'm trying to run some custom javascript from within my symbol component. It works fine when I run on the client but as soon as I set the conditional the `state.product` is not populated.

I have an input field of type `map` on my symbol.

The code looks like this, is there something I'm missing?

```
async function main() {
    if (Builder.isServer || Builder.isEditing) {
        await fetch('/api/product?sku=LEATHER_PURSE')
            .then(res => res.json())
            .then(data => {
                state.product = data;
            });
    }
}

export default main();
```

**Comment by steve8708** [comment]
hey @homanp we have a suggestion over in the original post for this in the forum https://forum.builder.io/t/running-custom-javascript-ssr-doesnt-seem-to-work/81

**Comment by homanp** [comment]
@steve8708 ok cool, got it. Closing this.

**Comment by homanp** [comment]
@steve8708 reopening this as per the forum thread https://forum.builder.io/t/running-custom-javascript-ssr-doesnt-seem-to-work/81

**Comment by mrkoreye** [comment]
Did the fix we made a few weeks ago work for you? Just following up to make sure we resolved this issue.

**Comment by homanp** [comment]
@mrkoreye seems to work fine now yes!
