### ISSUE TITLE
Change SDKs to wait on Editor event rather than eagerly run code to determine if SDK is running inside an editor.

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/builder#1807]
## Problem description

Currently, the SDK eagerly runs con on hydration to determine if it is running in an editor, so it then sets up a communication channel between the editor and the SDK.

The issue with this approach is that the SDK runs code eagerly. Hydration FWs already run so much code eagerly that the extra bit makes no difference, but Qwik goes out of its way to not run code, and this function forces it to run code eagerly, which negatively impacts SDK startup performance.

## Solution

The solution is to have the Builder.io Editor fire an event into the iframe containing the SDK. The SDK listens to the event and if it receives it, it will wake up the relevant code to set up the communication between the SDK and the Builder.io editor.

## Relevant code

The relevant code [render-content.lite.tsx](https://github.com/BuilderIO/builder/blob/0425af5b64a9076c7c40cc1d118f3d98a1139d47/packages/sdks/src/components/render-content/render-content.lite.tsx#L287-L363) contains `onMount()`. 

If you look closely the file looks something like this:
```typescript
  onMount(() => {
    if (isBrowser()) {
      if (isEditing()) {
         // Run code to connect Builder.io editor with the SDK
      }
    }
  });
```

Notice how the function executes eagerly just to check if it is in the browser and in the editor. If not in the editor it does nothing, but we already paid the cost of eager code download and execution. 

The above function needs to be turned into something like this:
```typescript
useOnWindow('builderio-connect-editor', $(() => {
         // Run code to connect Builder.io editor with the SDK
}));
```

NOTE: `builderio-connect-editor` is just a suggested name for a custom event that we should fire to cause the SDK to wake up and under the content.

**Comment by mhevery** [comment]
https://builder-io.atlassian.net/browse/ENG-3355

**Comment by samijaber** [comment]
This has been done in 0.7.1:

https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/qwik/CHANGELOG.md#071
