### ISSUE TITLE
No API in @builder.io/react to eager load image to improve LCP

### ISSUE THREAD

**Issue by mhuretski** [BuilderIO/builder#1818]
Hi, currently images in @builder.io/react can't have eager loading (only pixel have), lighthouse warns that Largest Contentful Paint has loading = lazy  https://github.com/BuilderIO/builder/blob/d9db5dc4ca3d225847d0f603a1e5557407ea6719/packages/react/src/blocks/Image.tsx#L345

Could you add a flag to set image loading eager or perhaps there's any other way to improve LCP loading speed?

**Comment by IgorDevJS** [comment]
Where can I enable this option, please? I updated the SDK, but I can't find it in the Builder.io interface.

**Comment by mrkoreye** [comment]
@IgorDevJS once you update to the latest SDK, then you can drag an image block on to the content entry, double click the image to bring up the options overlay, scroll towards the bottom, then click "advanced" where you will find a "high priority" setting. Toggling that setting will ensure eager loading of images.

**Comment by samijaber** [comment]
See https://github.com/BuilderIO/builder/blob/main/packages/react/CHANGELOG.md for which version number to use: `3.2.9`

**Comment by IgorDevJS** [comment]
Found it!! Thank you very much, everyone!!
