### ISSUE TITLE
Extra padding gets added to Builder-text component in builder/sdk-qwik

### ISSUE THREAD

**Issue by akshatgarg12** [BuilderIO/builder#1822]
**Describe the bug**
Some extra padding gets added to the builder-text component when integrated with builder/sdk-qwik, which makes the builder-text component look different in comparison to react sdk

**To Reproduce**
1. Create a content space in builder and add a text component
2. Integrate builder into your qwik app using builder/sdk-qwik
3. Integrate the same builder space in a react app
4. Notice the difference

**Expected behavior**
The text component should look similar in qwik and react

**Screenshots**
![Screenshot 2023-02-08 at 10 29 14 AM](https://user-images.githubusercontent.com/60404253/218408498-9332817d-010c-410d-92a8-861ba0bda413.png)
![Screenshot 2023-02-08 at 10 29 06 AM](https://user-images.githubusercontent.com/60404253/218408506-a7ead92d-edfd-45f1-908a-4ee5e0eed2d3.png)

**Additional context**
When comparing the styles of the rendered output , found out that these [textCSS](https://github.com/BuilderIO/builder/blob/main/packages/react/src/blocks/Text.tsx#L62) styles are missing from the text component in `builder/sdk-qwik` , this issue got resolved when I manually added these styles to the builder-text class in the project scope.

**Comment by samijaber** [comment]
@akshatgarg12 looking into this now. Could you please provide a link to that example in particular Simple/plain text blocks do not suffer from the styling issue.

**Comment by akshatgarg12** [comment]
Hey this is a minimal repro of the above issue
https://builder.io/content/ed2aab7792a741b8b41b76f2f0ee7ea3/edit?activeDesignerTab=0
