### ISSUE TITLE
Solid SDK: generateContentUrl does not allow for includeUnpublished

### ISSUE THREAD

**Issue by RyanPnayR** [BuilderIO/builder#1823]
**Describe the bug**
When trying to see changes locally outside of the builder cms window. The SDK does not allow for [this](https://www.builder.io/c/docs/query-api#code-include-unpublished-code )

**To Reproduce**
1. Use the SDK to get content

```
    getContent({
      model: "page",
      apiKey,
      includeUnpublished: true,
    }).then((content) => {
      setContent(content);
    });
```
2. Inspect the page on your site
3. In the network inspector see the request does not have `&includeUnpublished=true` in the url.

**Expected behavior**
All [API options ](https://www.builder.io/c/docs/query-api)should be available in the sdk.

**Comment by samijaber** [comment]
@RyanPnayR I updated these docs to have examples for the Solid SDK. https://www.builder.io/c/docs/query-api#code-include-unpublished-code

this particular field should go under `options`.
