### ISSUE TITLE
[docs] Querying sorting section is empty

### ISSUE THREAD

**Issue by ojvribeiro** [BuilderIO/builder#1892]
**Describe the bug**
As in the title, the section in the docs about sorting is empty: https://www.builder.io/c/docs/querying#sorting

**Screenshots**

![image](https://user-images.githubusercontent.com/8026741/224504247-49dbc62e-6383-403f-a214-a4b62d558f21.png)

**Additional context**
Tried to find information here on GitHub as well, didn't find any.

**Comment by kapunahelewong** [comment]
So glad you found it, @ojvribeiro. I didn't think to mention that content. If there's anything else you find or have feedback about on the docs, just let me know. Thank you!
