### ISSUE TITLE
Unable to fetch  insights data

### ISSUE THREAD

**Issue by amasaraure** [BuilderIO/builder#1895]
**Describe the bug**
I cannot get any metrics  data when I click the insights tab

**To Reproduce**
1. Create a landing page
2. Use HTML API to serve it from server side from a .net core application
3. Interact with landing page by submitting form
4. Can recieve form entries via email or custom actions/webhooks but no metrics are recorded

**Expected behavior**
Metrics should be displayed for interactions with landing page, Instead I get am HTTP code 500 error in the debugging console. error see screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/57103839/225105950-cda97dee-347a-438f-86df-34c4556a9cc0.png)

**Additional context**
I  have the growth plan trial license and it has not expired yet.

**Comment by samijaber** [comment]
@amasaraure Are you still experiencing this issue? I am closing this issue due to staleness, but please feel free to reopen if you still have issues with Insights.
