### ISSUE TITLE
Write followed by getAll doesnt return results

### ISSUE THREAD

**Issue by nuurcodes** [BuilderIO/builder#1902]
Hey, I am writing content to a model using the admin key which works fine. Then I try getAll which returns 0 results even though the items show up in the dashboard

If I write a second time, getAll works fine

```
await post(`https://builder.io/api/v1/write/p-14`, {
      name: content.title,
      published: "published",
      data: content,
    })
    
await builder.getAll("p-14", {
    limit: 100,
  }) //returns empty array after the first write
```

**Comment by samijaber** [comment]
I believe this is a caching issue. There is a chance that a GET request made immediately after your write does not reflect the latest content just yet
