### ISSUE TITLE
@builder.io/angular Data passing and custom actions not persist in builder.io state

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#191]
Hello, 
I trying to pass `data` to builder component like this
```
<builder-component *ngIf="visible"
                     [data]="data"
                     [model]="computedModel$ | async"
                     [options]="optionsCombined"
                     [reloadOnRoute]="false"
                     [handleRouting]="true"
                     [prerender]="false"
                     [navigationTimeout]="false"
                     (load)="load($event)"
                     (route)="routeChanged($event)"
                     (error)="error($event)">
 </builder-component>
```

The `data` includes some properties:
`data = { myFunc: () => alert('wooow!'), b: 'c'};`

But when I tried to read it from the state in builder.io I am getting an error:
```
Builder custom code error: state.myFunc is not a function in console.log(state.myFunc()) 
```
![image](https://user-images.githubusercontent.com/22659410/85844931-c623ab00-b7a3-11ea-9904-977b51d64eef.png)

I am 100% it was working fine a few months back.

Note: I am using `prerender=flase`
Note 2: Not working with ` "@builder.io/angular": "1.1.10"` and  `"@builder.io/angular": "1.1.11-alpha.2"`

**Comment by ca136** [comment]
We may have a fix for this, going to test it out locally now. I'll update this issue when I have more information.

**Comment by lyczos** [comment]
Thanks @ca136 , waiting for feedback :)

**Comment by ca136** [comment]
https://github.com/BuilderIO/builder/pull/192 for reference. due to Angular issues it's hard to test with npm linking so still want to make sure it doesn't break anything. Will have a pre-release candidate for you to test hopefully today.

**Comment by ca136** [comment]
@lyczos can you give this version a try locally or on your dev site and let me know if the function binding and all of your other content rendering works: `@builder.io/angular: "1.1.11-alpha.3"`

**Comment by lyczos** [comment]
After version update inside builder.io editor:
![image](https://user-images.githubusercontent.com/22659410/86101473-984ba880-baba-11ea-8609-62d2885c94dd.png)

The page is not rendering at all ;(

**Comment by ca136** [comment]
Got it thanks for testing, do you mind sharing your `<builder-component>` snippet?

**Comment by lyczos** [comment]
> Got it thanks for testing, do you mind sharing your `<builder-component>` snippet?

Sure @ca136 , it is already in issue report :)

```
<builder-component *ngIf="visible" <-- true after route change
                     [data]="data" <--  { myFunc: () => alert('wooow!'), b: 'c'}
                     [model]="computedModel$ | async" <-- "page"
                     [options]="optionsCombined"  <-- {cacheSeconds: 1000}
                     [reloadOnRoute]="false"
                     [handleRouting]="true"
                     [prerender]="false"
                     [navigationTimeout]="false"
                     (load)="load($event)"
                     (route)="routeChanged($event)"
                     (error)="error($event)">
 </builder-component>
```

**Comment by ca136** [comment]
Ok thanks :D can you give this a shot: @builder.io/angular: 1.1.12-1

**Comment by lyczos** [comment]
@ca136  `@builder.io/angular: 1.1.12-1`
```
data = {
    please: () => alert('I have a hope it will work!'),
    noWay: 'a'
  };
```
In builder:
![image](https://user-images.githubusercontent.com/22659410/86779719-2a742380-c05c-11ea-8721-1a238da7231d.png)

Output after click event:
![image](https://user-images.githubusercontent.com/22659410/86779829-47a8f200-c05c-11ea-9708-4bab7ba6cfa8.png)


I've checked also old versions and it seems to not work too `"@builder.io/angular": "1.0.83",` so maybe the issue is with some scripts from yours builder.io `/dist`

**Comment by ca136** [comment]
@lyczos I took a deeper look at this and the fix looks more complicated than we originally envisioned. We plan on re-writing our Angular SDK in the next couple of weeks, and we can make sure support for this gets into that project. The new version should be a lot simpler, lighter weight and easier to contribute to. Please let us know if you have any questions in the meantime.

**Comment by vishalvora** [comment]
@ca136 is this issue resolved?

**Comment by tomekknowde** [comment]
@cat136, any progress with this issue?
