### ISSUE TITLE
@builder.io/sdk-react : types and import errors

### ISSUE THREAD

**Issue by akshatgarg12** [BuilderIO/builder#1974]
**Describe the bug**

- [ ]  #2034

![Screenshot 2023-04-06 at 12 34 36 PM](https://user-images.githubusercontent.com/60404253/230302387-3e352365-ef24-4584-b30c-63076211ef86.png)

- [ ] #2035 

![Screenshot 2023-04-06 at 12 34 20 PM](https://user-images.githubusercontent.com/60404253/230299684-d0470379-2f5c-4650-a797-688a7021e721.png)

**To Reproduce**
1. `yarn add @builder.io/sdk-react`
2. `import {RenderContent, getAllContent} from '@builder.io/sdk-react'` in a page
3. use the RenderContent Component

**Expected behavior**
It should work render content without issues

**Additional context**

**Comment by samijaber** [comment]
Those are separate issues. 
- #1 is because we still aren't generating types at all. 
- #2 seem is a bit confusing. Maybe because we are not specifying the `.js` extension in the import (some ESM spec issue...)

**Comment by akshatgarg12** [comment]
- is it possible to generate types for sdk-react , like its generated for sdk-qwik?
- yeah its a ESM spec issue, it gets solved when all imports are appended with `.js` ,  but its required change to make the sdk usable. 

Should I create child issues for these separate problems?

**Comment by MadeByJay** [comment]
Has this issue been addressed yet? Still getting the kind of error the OP mentioned.

**Comment by samijaber** [comment]
This should now be fixed in the latest version `v0.5.2`
