### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by NHKK** [BuilderIO/builder#2]
Expected to work. What happened: Cannot find type definition file for lodash.

Reproduce steps:
1. ng new aproject --style=scss
2. cd aproject
3. npm install --save @builder.io/angular
4. add modules to app.module
import { BuilderModule } from '@builder.io/angular';
5. update app.component.html page with 
<builder-component model="page" (load)="contentLoaded($event)" (error)="contentError($event)">
  <div class="spinner"></div>
</builder-component>

![image](https://user-images.githubusercontent.com/18389319/63978278-ff0bca00-ca83-11e9-942c-154c030dcf33.png)

**Comment by steve8708** [comment]
Hi @NHKK, thanks for reporting! I have created a dev release that removes all lodash everywhere - could you try npm installing `@builder.io/angular@1.0.47-alpha.1` and let me know if that error still occurs for you?

**Comment by steve8708** [comment]
Going to close due to inactivity, @NHKK if this problem still persists for you after trying the latest alpha feel free to reopen this issue
