### ISSUE TITLE
Blank page with next js app router

### ISSUE THREAD

**Issue by PhilGarb** [BuilderIO/builder#2123]
**Describe the bug**
Published pages are blank when using next js app router. They show up fine in the preview.

**To Reproduce**
1. Please see the following [codesandbox](https://codesandbox.io/p/sandbox/stupefied-brahmagupta-qzirgd?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A27%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A27%7D%5D&file=%2Fapp%2F%5B...path%5D%2Fpage.tsx)
2. Edit the url to include: /home at the end.
3. See that the page is blank without any errors.

**Expected behavior**
I expect the page not to be blank or tell me what I have misconfigured.

**Additional context**
I understand that the main examples of integrating next js are using the pages directory. I do however not see why this should not work. It does work fine for the preview.

**Comment by mitchuman** [comment]
I've also tried setting up under `app/builder/[[...page]]/page.tsx` but am getting the error below (screenshot)

I've followed all the steps provided in the [official docs](https://www.builder.io/c/docs/integrating-builder-pages#add-a-builder-component-to-your-app) (Next App Router)

<img width="1034" alt="Screen Shot 2023-05-26 at 5 51 55 PM" src="https://github.com/BuilderIO/builder/assets/73133191/52308c3e-cd26-411a-85c0-18323c181676">

**Comment by JABvzla** [comment]
I found that if you add query param '?builder.preview=page' in the URL it show up.

**Comment by kno-raziel** [comment]
These people have  a mess, I have following the steps from the quick start for nextjs using app router, and the example doesnt work for me, then also tried to follow the example in their `[repo](https://github.com/BuilderIO/builder/blob/main/examples/next-app-directory/README.md)`  and didnt work for me and ended here looking for similar issues. 


All the examples uses different libraries, then found that they have [2 generations of SDKs ](https://www.builder.io/c/docs/sdk-comparison). Could some point me into a working example for nextjs with app router. Thanks

**Comment by samijaber** [comment]
Hey folks, we have updated our docs on using the App router. Take a look here: https://www.builder.io/c/docs/integrating-builder-pages#add-a-builder-component-to-your-app

These new docs should get your app working properly without the need for a query param change.

**Comment by hamatoyogi** [comment]
So I've checked the sandbox, and to get it working, all that's need to be done is update theses packages to their latest versions:
```
“@builder.io/react”: “^3.0.8",
“@builder.io/sdk”: “^2.0.5",
“next”: “^13.4.12",
```

Here's a link to a working SandBox: https://codesandbox.io/p/sandbox/strange-snow-84njm7

**Comment by HypernovaTX** [comment]
I am using `@builder.io/react` on version 3.1.1 with React 17 and followed the documentations posted above. Unfortunately the issue persists.

After some digging and trial-n-error, I have found a workaround that worked for me:

Instead of
```jsx
<BuilderComponent model="page" content={content} />
```
I used:
```jsx
<BuilderComponent model="page" data={content?.data} />
```

**Comment by samijaber** [comment]
Closing as I believe this is fixed now. We have also updated all of our docs around the App Router, and they should all be in working order.
