### ISSUE TITLE
Nested symbols aren't viewable in WYSIWYG editor

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#22]
Can’t see nested symbol in WYSIWYG when nesting symbols (adding symbols into symbols) in the same content model.

**Steps to reproduce**

* Create a symbol "foo" in model "Masters".
* Create a symbol "bar" in model "Masters". In Symbol "bar" add symbol "foo". Foo doesn't display in editor but you can view it in preview.

**Comment by JefferyReidKnowde** [comment]
Here's a video of the bug
https://www.dropbox.com/s/nhnoj9xcijar97z/2020-01-16_14-21-57.mp4?dl=0

**Comment by ca136** [comment]
This is a tricky one, we're looking into it but in the meantime you can refresh the page and both symbols should show up in the preview.

**Comment by steve8708** [comment]
Can confirm - this is driving us batsh*t crazy to figure out the source of, but will continue to investigate until we get it fixed!

**Comment by JefferyReidKnowde** [comment]
Sorry for delay. I’ll send whatever documentation I can find ASAP


Jeffery Reid | Chief Product Officer | Knowde | Mobile: 206-612-7009 | www.knowde.com

https://calendly.com/jefferyreid
