### ISSUE TITLE
App can't get stable with Angular 9

### ISSUE THREAD

**Issue by Zbenahmed** [BuilderIO/builder#221]
Using "@builder.io/angular": "1.1.13" it seems that our app can't get stable anymore when subscribing to it : 
https://angular.io/api/core/ApplicationRef#isStable

While digging into it, I discovered that there was a pending macrotask triggered by builder-component ( blocking the stable flag to turn to true )
<img width="498" alt="Screenshot 2020-07-23 at 16 31 52" src="https://user-images.githubusercontent.com/68016419/88306031-1e49c080-cd02-11ea-9ca3-a159c3e3c4a8.png">

When comparing to previous versions, it seems that this comes from here : https://github.com/BuilderIO/builder/blob/52d8d231f01fbcc2b9670368a47acdda57c1b349/packages/angular/src/app/modules/builder/directives/builder-content.directive.ts#L233

### Previous Behavior : 
This will create two macro tasks & two listeners, subscribed and on next event , one will cancel & invoke the task while the other resolve and invoke the task.

### Current Behavior : 
This seems to create two macro tasks but only one listener, subscribed and on next event, only the listener will resolve and invoke the task. Leaving the other macrotask unresolved.

**Comment by ca136** [comment]
Thanks for filing @Zbenahmed! We're planning a rewrite of our Angular SDK in the next few weeks and I'll try to ensure there's a fix for this in that release. I'll let you know when we have something to test.

**Comment by ocombe** [comment]
@ca136 do you have any update on the rewrite? We can't update to Angular v9 or v10 because of BuilderIO, it's the only thing holding us back...
Angular v9 was released almost a year ago 🤔
Is there anything we can do to help you migrate your code base?

**Comment by ca136** [comment]
Hi @ocombe, I'm hoping to start on the rewrite in the next week. Apologies that we're holding back your upgrade to Angular 9 and 10, our example app is using Angular 9 with the Builder SDK so we need to dig a bit deeper to find out why it's not working for some people.

Are you using SSR with Universal or are the zone.js issues happening in the browser as well?

**Comment by ocombe** [comment]
It's not working when we build the app for production (which is also the case in your demo). We opened another ticket here: https://github.com/BuilderIO/builder/issues/253

**Comment by ca136** [comment]
Got it, thanks for the additional information. Before I start on the SDK re-write I'll take a look at the production build and see if there are any easy fixes to get this working for you.

**Comment by ca136** [comment]
@Zbenahmed I [updated the example app](https://github.com/BuilderIO/builder/pull/260) to work with Angular 10, are you still seeing the issue above?

**Comment by steve8708** [comment]
closing per the thread going cold, can reopen if anyone sees this issue again though
