### ISSUE TITLE
Please change layout in page talking about layout :)

### ISSUE THREAD

**Issue by BartoszHor** [BuilderIO/builder#2242]
**Describe the bug**
Layout overlaps

**To Reproduce**
1. Go to https://www.builder.io/c/docs/child-layouts

**Screenshots**
<img width="1425" alt="Screenshot 2023-05-12 at 11 38 25" src="https://github.com/BuilderIO/builder/assets/64915566/450d6fab-4b46-4fa1-a6fe-75af2f9b3e4f">

**Comment by kapunahelewong** [comment]
Ah, the irony. 😆 Thanks so much for letting us know, @BartoszHor.  All fixed! You might have to refresh. 🌸
