### ISSUE TITLE
Need ability to clear formatting from text editor

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#23]
Need ability to clear formatting from text editor

**Steps to Reproduce**
* Create a symbol with a text input and choose the HTML input type 
* Use this symbol on a page
* Get some formatted text from somewhere (another page) and copy it to clipboard
* Then, on paste the text edit input persists the formatting. This is good.
* However, often we want to paste formatted text into this input and then clear the formatting and then use the formatting controls to reformat the content. What would be nice is to have a "clear formatting" method in the control or to add a "paste as plain text" option.

**Comment by steve8708** [comment]
Hey Jeff - this exists - select the text that you want to clear formatting of and hit the "Tx" looking button button in the top right of the text editor after save

![image](https://user-images.githubusercontent.com/844291/71746925-218f6480-2e23-11ea-804e-e28fdebb9b9e.png)
