### ISSUE TITLE
Cannot find module '@builder.io/sdk-vue/vue3

### ISSUE THREAD

**Issue by workspace** [BuilderIO/builder#2303]
## Describe the bug
I am encountering an error message that says "Cannot find module '@builder.io/sdk-vue/vue3' or its corresponding type declarations."

## To Reproduce

1. Import the '@builder.io/sdk-vue/vue3' module in a Vue 3 project.
2. Attempt to use the imported module in code.
3. Encounter the error message "Cannot find module '@builder.io/sdk-vue/vue3' or its corresponding type declarations."

## Expected behavior
I expected the '@builder.io/sdk-vue/vue3' module to be found and imported successfully without any error.

## Screenshots
<img width="626" alt="image" src="https://github.com/BuilderIO/builder/assets/7759511/151fb67d-b2ac-447d-9324-25bad8471a23">

## Additional context
- use pnpm as package manager.

**Comment by workspace** [comment]
@samijaber thanks!

**Comment by hansfuchs** [comment]
Any updates on this? It still appears to be broken.
