### ISSUE TITLE
Creating pages with Write API

### ISSUE THREAD

**Issue by dontmeway-axevil** [BuilderIO/builder#2312]
**Describe the bug**
I am creating page with Write API, then getting pages with proper query params, but newly created page does not return, only after some time it returns.

**To Reproduce**
1. Create model 
2. Send http POST request https://builder.io/api/v1/write/MODEL_NAME with proper body
3. Send http GET request https://cdn.builder.io/api/v2/content/MODEL_NAME with proper query params 
4. Newly created page will not return

**Expected behavior**
Created pages will return immediately

**Screenshots**

![Screenshot 2023-06-04 at 16 48 05](https://github.com/BuilderIO/builder/assets/134697933/8e1efa35-f38f-4a5a-9a80-fee5e5d0a323)
![Screenshot 2023-06-04 at 16 49 48](https://github.com/BuilderIO/builder/assets/134697933/4efef011-154d-4057-b76d-a65283714679)
![Screenshot 2023-06-04 at 16 50 05](https://github.com/BuilderIO/builder/assets/134697933/cdb68577-2bf6-4a91-9339-749bb212eec9)

**Comment by mrkoreye** [comment]
@dontmeway-axevil since the issue you are experiencing is related to the Builder platform and not the Builder SDK, can you please post your question in the Builder.io [forum](https://forum.builder.io/)? Our support team regularly monitors the forum and will be able to help you there. Thank you!
