### ISSUE TITLE
[angular] Could not make an angular element - multiple tries to create custom element

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#234]
Inside `BuilderModule` constructor - there is a code which trying to create angular element even if it already exists, that's why we are getting that issue:

![image](https://user-images.githubusercontent.com/22659410/89790225-ea540500-db21-11ea-875c-5382a91996c4.png)

Whole logic should be moved to another place (`forRoot` method). And fired only once on first init.
Right now, wherever we try to use `BuilderModule` with lazy loaded modules we will end up with this error.

I will add hot-fix as a part of today PR but I think it should be refactored and moved to separate place - outside `constructor`

**Comment by steve8708** [comment]
Thanks @lyczos ! Closing via #235 being merged
