### ISSUE TITLE
Add additional styles to predefined components?

### ISSUE THREAD

**Issue by ZYR0Z** [BuilderIO/builder#2398]
Is there a way to add additional styles to predefined components, like for example the `Text` Component? I only find in the Documentation, that u can override the Component, but I dont want to override the whole Component with my custom Component, i only want to add some more Styles to it, for exmaple, for every `Text` component, and text-transform: uppercase or a margin-bottom: 2rem. Is there a way to do this? I know that there are Templates in the Builder.io UI but it would be so much nicer to just apply some basic styling

**Comment by mrkoreye** [comment]
Hi @ZYR0Z ! In order to accomplish this I would suggest going with the override custom component route you mentioned. You can check out our [implementation of the component](https://github.com/BuilderIO/builder/blob/main/packages/react/src/blocks/Text.tsx), copy it, make your changes, and then register it as a custom component that overrides the built in one. As far as having a way to override the built in component styles directly, that would be a great feature request that you can submit here: https://ideas.builder.io/

**Comment by ZYR0Z** [comment]
Yeah but how do i do this, if i do it like in the documentation i get an webpack error, here is my code: [https://gist.github.com/ZYR0Z/45054b2ca91d62f3d247860aa3af75c3](https://gist.github.com/ZYR0Z/45054b2ca91d62f3d247860aa3af75c3)

**Comment by mrkoreye** [comment]
Oh interesting, yeah there seems to be an issue with webpack thinking the import on https://gist.github.com/ZYR0Z/45054b2ca91d62f3d247860aa3af75c3#file-text-tsx-L5 is supposed to be javascript but it is typescript, so it does not know what to do. Some options here are:
1. get webpack to recognize that the file is a `.ts` file and needs to be loaded with the typescript loader
2. try changing https://gist.github.com/ZYR0Z/45054b2ca91d62f3d247860aa3af75c3#file-text-tsx-L5 to `import { tryEval } from "@builder.io/react/dist/lib/src/functions/try-eval";`
3. Remove the `tryEval` code from the text component if you do not need to use `{{someStateValue}}` type expressions in your text blocks within Builder by changing https://gist.github.com/ZYR0Z/45054b2ca91d62f3d247860aa3af75c3#file-text-tsx-L134 to just be `__html: this.props.text || (this.props as any).content || ""`

**Comment by ZYR0Z** [comment]
I removed the try-eval function now, but now the `BuilderStoreContext` throws the same error, i think its because i import a specific file from a node_module and webpack doenst know how to handle it, i tried serval webpack configurations and loaders but all of them dont seem to work for me? could you please share a webpack config that solves this problem?

**Comment by ZYR0Z** [comment]
The issue is now resolved, i just changed it to be a .jsx file and its only one so i can live without it!

**Comment by mrkoreye** [comment]
Glad you got it resolved 😄
