### ISSUE TITLE
On content page, any saved filters overrides the “all” view until you actively refresh the page

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#25]
On content page, any saved filters overrides the “all” view until you actively refresh the page

Steps to reproduce

* Go to Content page (https://builder.io/content)
* Choose a content type with many pages
* Create a filter
* Save it as shared with Org
* Then, click this new shared filter to apply the filter
* next, click back on the content types and the filter you selected applies to all the views of data until you force a page refresh

**Comment by ca136** [comment]
Found and fixed the issue, should be in production early next week!
