### ISSUE TITLE
Builder Dev Tools fails to recognized Qwik components with a default export.

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/builder#2516]
**Describe the bug**

When exporting a component as default builder dev tools will not register the component, and it will fail to load.
```tsx
import { component$, useStore } from '@builder.io/qwik';

const MyFunComponent = component$((props: { text: string }) => {
  const state = useStore({
    count: 0,
  });

  return (
    <div>
      <h3>{props.text.toUpperCase()}</h3>
      <p>{state.count}</p>
      <button onClick$={() => state.count++}>Click me</button>
    </div>
  );
});

export default MyFunComponent;
```

Rather than

```tsx
export const MyFunComponent
```

**To Reproduce**
1. Create a Qwik app at latest and choose the Visual Site Editor preset.
2. Create a new component, and export it as default
3. Add it to builder-registry.ts
4. Check localhost:5173, and in the builder devtools, you should see the following error:
<img width="370" alt="image" src="https://github.com/BuilderIO/builder/assets/104264123/93732030-0ded-4406-810c-f8323aa65888">

-

**Expected behavior**
The component is correctly registered in builder dev tools after being added within the `CUSTOM_COMPONENTS` array of objects.
<img width="359" alt="image" src="https://github.com/BuilderIO/builder/assets/104264123/c8e2b2b5-a49b-4ab1-bc34-92ed6da47495">

Like the image above.

**Screenshots**
<img width="370" alt="image" src="https://github.com/BuilderIO/builder/assets/104264123/93732030-0ded-4406-810c-f8323aa65888">

**Additional context**
I'm using chrome on a windows 11 machine, and WSL2 in development

**Comment by adamdbradley** [comment]
Should be fixed in the latest release `@builder.io/dev-tools@0.1.12`, for reporting the issue!
