### ISSUE TITLE
@builder/sdk-react doesn't work in NextJS

### ISSUE THREAD

**Issue by sfcgeorge** [BuilderIO/builder#2526]
**Describe the bug**

The [@builder/sdk-react-nextjs docs](https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/nextjs) say that is just for the `app` directory. For the `pages` directory (what we use) it recommends using the @builder/sdk-react package.

The @builder/sdk-react package crashes because something something ESModules / CommonJS compatibility I guess. `Module not found: Can't resolve 'acorn'`. In my fiddling I've also seen errors like `SyntaxError: Unexpected token 'export'`

A similar issue was raised and fixed a while ago by adding `type: "module"` to the package.json (I haven't confirmed this worked) https://github.com/BuilderIO/builder/issues/1217#issuecomment-1219996867

According to the changelog though, `type: "module"` was removed again https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/react/CHANGELOG.md#050

**To Reproduce**

Copy example config into a new NextJS project like this; https://stackblitz.com/edit/stackblitz-starters-vf5yip?file=pages%2Findex.js

**Screenshots**

<img width="1494" alt="Screenshot 2023-08-03 at 18 13 34" src="https://github.com/BuilderIO/builder/assets/885003/0da456ea-3caf-4b4e-9aa6-1d61b964c12d">

**Additional context**

We would just use the old @builder/react package but we get hydration missmatch warnings where there's extra Emotion output. We use a newer version of Emotion and the Emotion compiler so I'm not too surprised that's unhappy. The SDK approach of not having such a dependency seems far more compatible.

**Comment by samijaber** [comment]
This is a known issue in the latest release of `@builder.io/sdk-react`. It is in the process of getting fixed, and we should have a solution out very soon. 

In the meantime, try version `0.5.1`

**Comment by sfcgeorge** [comment]
@samijaber Thanks for the speedy response and package update!

0.5.1 crashes with `./node_modules/@builder.io/sdk-react/dist/helpers/preview-lru-cache/init.js:6:0
Module not found: Can't resolve 'lru-cache'`. I tried changing the import to `'@builder.io/sdk-react/server'` as I saw that suggested somewhere but no difference. 

0.5.4 seems to throw the same error.

**Comment by samijaber** [comment]
Ah, sorry about that. You can workaround this temporarily by installing `lru-cache` in your app. I will be releasing a fix tomorrow that fixes this issue.

Thanks for reporting these issues!

**Comment by samijaber** [comment]
ok @sfcgeorge, `v0.5.5` should be all good to go now! Will keep this open waiting for final confirmation from you.

**Comment by sfcgeorge** [comment]
Thanks @samijaber, getting a little further, now seeing

```
error - /home/projects/stackblitz-starters-vf5yip/node_modules/@builder.io/sdk-react/dist/functions/get-content/index.js:1
import { TARGET } from '../../constants/target.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

https://stackblitz.com/edit/stackblitz-starters-vf5yip?file=package.json

**Comment by samijaber** [comment]
@sfcgeorge You need to add the following to your `next.config.js`:


```js
module.exports = {
  // the SDK needs to be transpiled
  transpilePackages: ['@builder.io/sdk-react'],
};
```

And for some reason, the `next` version you used was not behaving as expected. Updating to the latest version of next fixed it!

https://stackblitz.com/edit/stackblitz-starters-a2unxh?file=next.config.js


Closing this now as I have confirmed that the SDK is fully working with the above stackblitz link. Thanks a lot for your patience again @sfcgeorge 🙏🏽
