### ISSUE TITLE
Angular Components are not working with Ivy enabled after build process

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#253]
Description:
When the angular component decorated with `@BuilderBlock` is inserted into buiilder.io content it is normally working while we are using `npm start` but when we use `npm run build`  in place of the component we are seeing a blank space (tag is created in DOM). The issue appears only when `Ivy is enabled` 

NPM START:
![image](https://user-images.githubusercontent.com/22659410/91741940-c1211480-ebb5-11ea-943d-48bc6edc5a27.png)

NPM RUN BUILD:
![image](https://user-images.githubusercontent.com/22659410/91741959-c7af8c00-ebb5-11ea-8580-4440218e3b5c.png)

Repro steps:

1. Go to **angular example app** and serve it
2. Put there some content using builder.io
3. Everything working as expected
4. Now got to to the console and run `npm run build`
5. After build serve `dist`  (I've used `http-server` package)
**6. Result: No angular component**

**Comment by ca136** [comment]
@ocombe and @lyczos I was able to get the example repo working with Angular 10 here: https://github.com/BuilderIO/builder/pull/260

The build-optimizer was removing the Builder decorators used to register custom components:
https://www.npmjs.com/package/@angular-devkit/build-optimizer#scrub-file

So if you want to keep the build-optimizer on, you need to call `BuilderBlock` directly vs using it as a decorator, [see here](https://github.com/BuilderIO/builder/pull/260/files#diff-63161a870db7a1b4c3365a02d50b59c6R14). The ergonomics are a little weird so I made a ticket to expose a cleaner way of registering components without decorators. Should hopefully be done in one of the upcoming sdk releases. 

But just to confirm, you can use `BuilderBlock` today and be totally unblocked on Angular 10. Let us know if you run into any other issues!

**Comment by ocombe** [comment]
I can confirm that it works, thanks a lot!
