### ISSUE TITLE
Remove node-fetch from core?

### ISSUE THREAD

**Issue by gazal-k** [BuilderIO/builder#2554]
**Describe the bug**
This follows from the blog post here about not adding `node-fetch` as a dependency in your npm packages; https://www.builder.io/blog/stop-polyfilling-fetch-in-your-npm-package. This was addressed at the time by #1661. But it looks like there's been a lot of refactoring since then. `@builder.io/react` now depends on `@builder.io/sdk`, which in turn has a dependency on `node-fetch`; https://github.com/BuilderIO/builder/blob/b15b4ef7c1946b750b2797f5d43fdc29760ea208/packages/core/package.json#L71

Our application framework tries to add the dependency `2.6.12` of `node-fetch` which results in the error: `Didn't recognise the dynamic module ID: punycode`

**To Reproduce**
Steps to reproduce the behaviour:
1. Install `@builder.io/react` / add to dependencies
2. Use application framework with its own `node-fetch` dependency.

**Expected behaviour**
The application should be able to use the required version of fetch polyfill without any issues.

**Additional context**
To resolve the dependency issue, we have added a global override like:
```json
"overrides": {
  "node-fetch": "2.6.2"
}
```

**Comment by samijaber** [comment]
The blog post refers specifically to our new generation of SDKs: https://github.com/BuilderIO/builder/tree/main/packages/sdks/ . Those no longer have `node-fetch` as a dependency.

What yo are referring to is the gen1 React SDK: https://github.com/BuilderIO/builder/tree/main/packages/react

We still have not removed the `node-fetch` dependency from the older one.

**Comment by gazal-k** [comment]
Thanks, I guess I mistook the different folder structures for a refactor. Any estimate on when the new v2 SDKs would become GA / ready for production use?

**Comment by samijaber** [comment]
No clear timeline, but it's a high priority of ours and we're actively working on getting them to a stable release!

**Comment by gazal-k** [comment]
Thank you @samijaber. We'll keep an eye out 🙂
