### ISSUE TITLE
Invalid Regular Expression On Safari

### ISSUE THREAD

**Issue by FutureFutureTo** [BuilderIO/builder#2556]
**Describe the bug**
I am using most recent version of Builder with Next App Router. My pages work great on Chrome and Edge, but I get the following error on Safari:
Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name

**Comment by teleaziz** [comment]
Hi @FutureFutureTo I cannot reproduce, do you mind sharing a codessandbox or a repo with reproduction?

**Comment by FutureFutureTo** [comment]
hey there, apologies but I think this was due to another package that I had installed. I no longer have the error.
