### ISSUE TITLE
@builder/sdk-vue using improper styles for `BuilderColumns`

### ISSUE THREAD

**Issue by Joepocalyptic** [BuilderIO/builder#2560]
**Describe the bug**

The `@builder/sdk-vue` library (version 0.5.9) is not providing proper styles for the built-in `BuilderColumns` component. The `--flex-dir`, `--flex-dir-tablet`, and `.builder-columns-[etc]-breakpoints` styles are correctly being applied, but `display: flex` is not, rendering these styles inactive.

The result is that using the built-in `Columns` block with `@builder/sdk-vue` causes the children to always be stacked, also causing some visual bugs within the editor.

**To Reproduce**

1. Create a Vue or Nuxt application according to the Builder documentation
2. Drag a `Columns` component using the visual builder and try populating its slots
3. Inspect the result; `display: flex` should be absent from the `.builder-columns` element

**Expected behavior**

`display: flex` should be correctly applied to the `BuilderColumns` component

**Screenshots**

![image](https://github.com/BuilderIO/builder/assets/42530725/3299c080-3657-4da7-8b81-b1d91e89e167)
![image](https://github.com/BuilderIO/builder/assets/42530725/2f2a14d1-7d30-4b97-bc6a-22876e93a933)

**Additional context**

From my understanding of the codebase, it seems that the Vue component is generated from the `columns.lite.tsx` file using Mitosis. The code for this component has the following attribute:
```jsx
css={{
  display: 'flex',
  lineHeight: 'normal',
}}
```
([Source](https://github.com/BuilderIO/builder/blob/449e5c8a9ff69af3344567bf0d5ce86c6c9a4437/packages/sdks/src/blocks/columns/columns.lite.tsx#L182-L185))

Perhaps this is an upstream bug in Mitosis where the direct CSS is not being applied? I think I found the compiled Vue render function, and both `display: flex` and `lineHeight` are nowhere to be found; only the CSS variables are being applied:

https://gist.github.com/Joepocalyptic/7dc18e54853bc1ddc0959ff8d7f004b0

**Comment by samijaber** [comment]
Thanks for filing. You are missing the CSS stylesheet import. Here is how it's done in the vue-3 example project:

https://github.com/BuilderIO/builder/blob/31b4fc3cd2029401193f9480b884001d384588f8/examples/vue/vue-3/src/App.vue#L3

We will update the package docs to remind users that this import is needed for the library to work!
