### ISSUE TITLE
Symbols to 100% height of the non-symbol parent container / Optionally render BuilderBlocks without wrapper element for its children

### ISSUE THREAD

**Issue by DmacMcgreg** [BuilderIO/builder#2570]
**Describe the bug**
I've found a pretty huge issue that very well might prevent us from adopting Builder... I'm not sure why this issue has been put aside for so long, but it's a pretty big one for us, because if we're going to have custom symbols or react components, we want to be able to have them take up the full height of the container without the non-technical user adding custom CSS to the elements or containers. it seems like it's one of the highest voted issues on your ideas/forums as well. Could we maybe add a toggle to add the required flex attribute on it, or change the rendering behaviour somehow? 

[Optionally render BuilderBlocks without wrapper element for its children](https://ideas.builder.io/ideas/PROD-I-134)
[Symbols to 100% height of the non-symbol parent container](https://forum.builder.io/t/symbols-to-100-height-of-the-non-symbol-parent-container/3182/8)

**To Reproduce**
(copied from the forum post):
We have a grid layout container that we are filling with symbols, whose uppermost container has a height of 100% in order for all the symbols to be of the height of the tallest symbol in the grid.
The problem is that symbols do not seem to expand to the height of the non-symbol container when they are imported. From what I understand, when imported, symbols get wrapped in more containers automatically, that do not have the styling.

Is styling propagation something that could exist in the future for symbols?
What would be the best solution now, except to fix symbol height as we would like them to be flexible?

**Expected behavior**
Symbols should fill height of parent container

**Screenshots**
![image](https://github.com/BuilderIO/builder/assets/3266023/113fe5c4-a359-44d4-84f3-6ec75447d93e)

**Additional context**
Highly voted issue in ideas/forum.
Potential blocker for adopting for multiple clients.

**Comment by samijaber** [comment]
As of 0.9.0 we provide a `BlocksWrapper` and `BlocksWrapperProps` props to `Content` that allows you to customize this component, and provide props to it: https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/vue/CHANGELOG.md#090

You should be able to use `BlocksWrapper` to customize the `div` that wraps the array of blocks. As of today, all Symbols are still always rendered with a wrapping `div` of their own however.

Does the `BlocksWrapper` prop unblock you?

**Comment by DmacMcgreg** [comment]
The purpose is really to say that the responsibility for passing custom css should not be something delegated to a non-technical user. Rather, they should be able to add the elements without having to know technical details and it should just work. This would unblock if there is some simple way to show to the user why the layout is being broken when it should work correctly and not depend on some opaque implementation details from the CMS..

Could you give an example of how the BlocksWrapper would be used to accomplish this?

**Comment by samijaber** [comment]
The `div` exists to allow for a smooth experience in the visual editor. There are no plans to change that logic, as it would break the experience/layout of every current user.

Adding the `BlocksWrapper` prop would be something a technical user does only once in the webapp when integrating/calling the SDK. non-technical teammates should not have to worry about this detail.

Here is some pseudocode of what I mean:

```tsx
<Content content={content} apiKey={apiKey} blocksWrapperProps={{ style: { display: 'contents' } }} />
``` 

This would keep rendering the `div`, but with a `display: 'contents'` CSS property which will essentially remove the 'div' from the layout (https://developer.mozilla.org/en-US/docs/Web/CSS/display#contents)

**Comment by DmacMcgreg** [comment]
Great, seems reasonable then!

**Comment by samijaber** [comment]
We will work on adding some documentation highlighting how this can be done. Thanks!
