### ISSUE TITLE
GraphQL error when multiple URL's per page is enabled

### ISSUE THREAD

**Issue by k-schneider** [BuilderIO/builder#2587]
**Describe the bug**
After enabling multiple URL's per page I started receiving an error when requesting a page's URL via the Graph API.

**To Reproduce**
1. Enable multiple URL's in advanced settings
2. Add multiple URL's to a page (example homepage)
3. Execute this query

```
query {
  page(target: { urlPath: "/" }) {
    name
    data {
      url
    }
  }
}
```

You will receive an error similar to:

```
{
  "errors": [
    {
      "message": "String cannot represent value: [\"/\", \"/en\", \"/fr\"]",
      "details": null
    }
  ],
  "data": {
    "page": [
      {
        "name": "Homepage",
        "data": {
          "url": null
        }
      }
    ]
  }
}
```

**Expected behavior**
I'd expect that url would return an array of strings if multiple are defined.

**Comment by teleaziz** [comment]
we released a fix to the API this morning, thanks for reporting this issue.
