### ISSUE TITLE
Critical Usability Issue: Flash of unstyled content in `@builder.io/sdk-svelte` due to Mitosis translation bug

### ISSUE THREAD

**Issue by AlbertMarashi** [BuilderIO/builder#2632]
**Describe the bug**
Flash of unstyled content in `@builder.io/sdk-svelte` due to Mitosis translation bug.

The [source code here](https://github.com/BuilderIO/builder/blob/31b4fc3cd2029401193f9480b884001d384588f8/packages/sdks/src/components/inlined-styles.lite.tsx) 

```tsx
interface Props {
  styles: string;
  id?: string;
}

export default function InlinedStyles(props: Props) {
  return <style innerHTML={props.styles} id={props.id} />;
}
```
gets converted to
```svelte
<script context="module"></script>

<script>export let styles;
export let id = undefined;
</script>

<svelte:element this={"sty" + "le"} {id}>{@html styles}</svelte:element>
```

This has the side effect that during SSR, svelte injects `<!-- HTML_TAG_START -->` comment **inside** the `<style>` tag. This is invalid code because HTML comments do not work in `CSS`. The tag is inserted because Svelte uses these comments for client-side hydration and mounting.

**To Reproduce**
1. Create any page in builder.io
2. Use SvelteKit integration
3. Render the page without javascript
4. There will be no styling because the CSS `<style>` tags injected into the page cannot be parsed by the browser

**Expected behavior**
Styling should work on first page load

**Proposed Fix**
I am not knowledgeable about the inner workings of mitosis but here is what the generated svelte code should look like:
```svelte
<script>export let styles;
export let id = undefined;

$: style_tag = `<style id="${id}">${styles}</style>`;

</script>
{@html style_tag}
```

**Screenshots**

![image](https://github.com/BuilderIO/builder/assets/17972275/412bbefb-466e-4c67-a33f-7bb91a45361e)

**Additional context**

**Comment by AlbertMarashi** [comment]
@samijaber do you have any ETA for when this might get fixed? It's probably affecting every svelte site using builder.io and preventing our organisations projects from adopting it.

Thank you in advance

**Comment by AlbertMarashi** [comment]
@samijaber happy to attempt giving this a PR if you can point me in the right direction

**Comment by samijaber** [comment]
Hey @AlbertMarashi, thanks for filing this bug. We are still looking into the issue and will report back when we have an update.

**Comment by samijaber** [comment]
@AlbertMarashi We fixed a styling bug in the latest SDK: v0.6.3

I believe it should fix your issue. Could you test it and let me know?

**Comment by AlbertMarashi** [comment]
Hi @samijaber

No unfortunately it did not fix the issue the issue arises from [this mitosis component](https://github.com/BuilderIO/builder/blob/31b4fc3cd2029401193f9480b884001d384588f8/packages/sdks/src/components/inlined-styles.lite.tsx) being improperly converted to Svelte code

The output of the component looks like this:
```svelte
<script context="module"></script>

<script>export let styles;
export let id = undefined;
</script>

<svelte:element this={"sty" + "le"} {id}>{@html styles}</svelte:element>
```

The particular issue is this section `{@html styles}` - Svelte is adding a HTML comment inside the CSS which is not valid CSS and breaks parsing.

There's a few ways to correctly approach this in svelte:
```
<script>export let styles;
export let id = undefined;
</script>

{@html `<style id="${id}">${styles}</style>`}
```

Or:
```svelte
<script>
export let styles;
export let id = undefined;

$: style_tag = `<style id="${id}">${styles}</style>`;

</script>
{@html style_tag}
```

**Comment by AlbertMarashi** [comment]
This is actually kind of doubly worse, because the exact same issue is occuring with Script tags
```svelte
<script context="module"></script>
<script>export let scriptStr;
export let id = undefined;
</script>

<svelte:element this={"script"} {id}>{@html scriptStr}</svelte:element>
```

**Comment by AlbertMarashi** [comment]
https://github.com/sveltejs/svelte/issues/9341 I created an issue for this in Svelte but I believe this is a mitosis bug rather than a Svelte bug (although svelte should be warning about this or something)

**Comment by dominikg** [comment]
here's an example of the approach @AlbertMarashi  mentioned above https://svelte.dev/repl/0c0942ba74b74d82a2f19c024053775a?version=4.2.2

Note: to ensure svelte preprocess does not pick up the style tag, it also has to be broken up/escaped in string literals, there are several ways to do this, rg the + concatenation in the original mitosis output or putting parts of it in a template expression.

**Comment by dominikg** [comment]
And maybe even more important: 
> Svelte does not sanitize expressions before injecting HTML. If the data comes from an untrusted source, you must sanitize it, or you are exposing your users to an XSS vulnerability.

https://svelte.dev/docs/special-tags#html

If mitosis emits code that allows untrustred/unescaped content in script or style tags this way, it should be documented.

**Comment by AlbertMarashi** [comment]
@samijaber this seems to be like a major show stopper from anyone seriously adopting builder.io for SvelteKit websites, having FOUC is a relatively large SEO, and accessibility issue, not to mention this issue is also prevalent in `<script>` tags because it uses a similar mitosis component

**Comment by samijaber** [comment]
@AlbertMarashi we have found the fix and are doing some final testing. A new version without the issue will be released very soon.

**Comment by samijaber** [comment]
Version 0.6.4 of the Svelte SDK should have a fix for the FOUC. SSR'd content should now have styles rendering properly.

We added a bunch of testing that shows styles working. I am going to mark this issue as closed, but feel free to comment/reopen if you see otherwise.

**Comment by AlbertMarashi** [comment]
@samijaber awesome looks to be working now
