### ISSUE TITLE
Handy editor of native "Text" component doesn't update it's value (Svelte)

### ISSUE THREAD

**Issue by sesa736123** [BuilderIO/builder#2647]
**Describe the bug**
Handy editor of native "Text" component doesn't update it's value. When I update the text inside rich text editor then it works but handy text editor doesn't update it. 
This issue appears in Svelte project but in React project I couldn't see such an issue.

**To Reproduce**
1. Add native "Text" component
2. Edit it's value by directly editing the text, without using rich text editor
3. Value doesn't change in layers (screenshot)

**Expected behavior**
To update the text

**Screenshots**
I changed the text in handy text editor and it didn't update in the layers section
<img width="565" alt="Screenshot 2023-10-17 at 11 05 39" src="https://github.com/BuilderIO/builder/assets/142589501/7a9d5efa-4894-4109-b12b-9d4406598b9d">

**Comment by samijaber** [comment]
The layers section shows the title of the element. not its content. You can edit the title by double clicking on the item in the layers sidebar.
