### ISSUE TITLE
Changes made to content in the block text editor don't trigger save action

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#28]
When I view a published page and make changes to existing text content using the block text editor, the app doesn't detect this as a state change which means I can't publish these edits. 

To workaround this, one has to make a change to the page the app does recognize like changing a style settings.

Can you update so that simply text changes are detected and prompt the "publish" action. thanks.

**Comment by ca136** [comment]
@JefferyReidKnowde do you mind sharing a video or sending me a link where you're seeing the issue? I tried this out on a few of our own pages and wasn't able to reproduce.

**Comment by JefferyReidKnowde** [comment]
Yes. will do

**Comment by JefferyReidKnowde** [comment]
I'm happy to say that I can no longer reproduce it. You can close this and if I run into it again, I'll grab a video. Thanks!

**Comment by ca136** [comment]
Awesome, thanks!
