### ISSUE TITLE
Incorrect email provided

### ISSUE THREAD

**Issue by coderbm1** [BuilderIO/builder#2850]
Hey

**Describe the bug**
Incorrect email provided - builder.io security site.

**To Reproduce**
1. Go to https://www.builder.io/c/security
2. Search for (or scroll down to see): "Builder is SOC2 Type 2 compliant. [Contact us](mailto:%20sales@builder.io) for more details"
3. Click or copy value from `Contact us` part
4. See: `mailto:%20sales@builder.io` instead of `mailto:sales@builder.io`

**Expected behavior**
Should be without `%20`

**Screenshots**
NA

**Additional context**
NA

**Comment by samijaber** [comment]
Fixed, thanks for reporting!
