### ISSUE TITLE
Fresh installation of `@builder.io/react` throws error

### ISSUE THREAD

**Issue by RafalFilipek** [BuilderIO/builder#2885]
**Describe the bug**
Fresh installation of `@builder.io/react` throws error

**To Reproduce**

```bash
mkdir bug
cd bug
npm init -y
npm install -E @builder.io/react@latest
```

**Expected behavior**
No error

**Screenshots**
```
npm ERR! code 1
npm ERR! path /[...]/node_modules/isolated-vm
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.15.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.15.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.11.6 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: ENOENT: no such file or directory, stat './pacakage.json'
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/[...]/versions/node/v18.15.0/bin/node" "/[...]/versions/node/v18.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! cwd /[...]/node_modules/isolated-vm
npm ERR! gyp ERR! node -v v18.15.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /[...]/.npm/_logs/2023-12-18T21_15_47_788Z-debug-0.log
```

**Additional context**
This line is important

```
npm ERR! gyp ERR! stack Error: ENOENT: no such file or directory, stat './pacakage.json'
```

There is a typo in some script.

```
system: macos
npm: 9.5.0
node: v18.15.0
```

Thank you,

Rafał

**Comment by samijaber** [comment]
I am unable to reproduce, using the same npm/node versions as you on a clean project (I created an empty folder and ran `npm init -y` before the screenshot:

![CleanShot 2024-01-02 at 16 46 48@2x](https://github.com/BuilderIO/builder/assets/1393142/a90125ba-74c6-485b-87e0-8ea327445adf)

I'm on an M1 mac, not sure if that makes any difference.

**Comment by andrea-mmo** [comment]
I'm also experiencing the same issue
```
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/2] ⠠ waiting...
error /Users/luigiderson/Repos/Veo/circkit-website/node_modules/isolated-vm: Command failed.
Exit code: 127
Command: prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
Arguments:
Directory: /Users/luigiderson/Repos/Veo/circkit-website/node_modules/isolated-vm
Output:
prebuild-install warn install No prebuilt binaries found (target=18.18.2 runtime=node arch=arm64 libc= platform=darwin)
/bin/sh: node-gyp: command not found
```

```
node -v
v18.18.2

yarn -v
1.22.19
```

**Comment by RafalFilipek** [comment]
In your case it looks like you're missing node-gyp

> node-gyp: command not found

Did you try to install with nom on the exact same machine. 

Can you try 'which node-gyp' in your terminal?

Regarding my case. 
Maybe this is somehow related to macOS m2 processor etc? No idea :/

**Comment by andrea-mmo** [comment]
> In your case it looks like you're missing node-gyp
> 
> > node-gyp: command not found
> 
> Did you try to install with nom on the exact same machine.
> 
> Can you try 'which node-gyp' in your terminal?
> 
> Regarding my case. Maybe this is somehow related to macOS m2 processor etc? No idea :/

Yeah that worked thank you @RafalFilipek

**Comment by samijaber** [comment]
@RafalFilipek are you still facing issues? Did the workaround you provided to @andrea-mmo work for you?
