### ISSUE TITLE
Animations not supported in Svelte SDK

### ISSUE THREAD

**Issue by cadamsdev** [BuilderIO/builder#2889]
**Describe the bug**
When setting the hover styles the hover styles do not apply.

**To Reproduce**
See attached video. (I am using the Sveltekit)
https://github.com/BuilderIO/builder/assets/12568665/28686b95-98cc-4a2d-a7ff-71be6fa7ce03

**Expected behavior**
There should be hover styles.

**Screenshots**
See video

**Comment by samijaber** [comment]
Animation tab is currently not supported in Svelte SDK. See the features matrix here:

https://github.com/BuilderIO/builder/blob/main/packages/sdks/README.md#features


We will disable the button soon to avoid confusion

**Comment by samijaber** [comment]
As of 0.12.7, we support animations! https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/svelte/CHANGELOG.md#0127

Closing this.
