### ISSUE TITLE
Nuxt Build fails for catch-all page (symbol has already been declared)

### ISSUE THREAD

**Issue by 20x-dz** [BuilderIO/builder#2925]
**Describe the bug**
Deploying to vercel/[building nuxt](https://nuxt.com/docs/getting-started/server#universal-deployment) with the [nitro preset for vercel](https://nitro.unjs.io/deploy/providers/vercel) fails with the following errors when using a [catch-all page](https://github.com/BuilderIO/builder/tree/70fa50d604bebad042813d3460805752185736ca/examples/vue/nuxt-3-catchall):

```
 ERROR  Transform failed with 3 errors:                               23:16:38
/Users/me/builder-vue-test/.nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:1204:3: ERROR: The symbol "getCookie" has already been declared
/Users/me/builder-vue-test/.nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:1211:3: ERROR: The symbol "setCookie" has already been declared
/Users/me/builder-vue-test/.nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:2543:3: ERROR: The symbol "createEvent" has already been declared

  .nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:1204:3: ERROR: The symbol "getCookie" has already been declared
  .nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:1211:3: ERROR: The symbol "setCookie" has already been declared
  .nuxt/dist/server/_nuxt/_...app_-s51JPBQE.js:2543:3: ERROR: The symbol "createEvent" has already been declared
  at failureErrorWithLog (node_modules/esbuild/lib/main.js:1651:15)
  at node_modules/esbuild/lib/main.js:849:29
  at responseCallbacks.<computed> (node_modules/esbuild/lib/main.js:704:9)
  at handleIncomingPacket (node_modules/esbuild/lib/main.js:764:9)
  at Socket.readFromStdout (node_modules/esbuild/lib/main.js:680:7)
  at Socket.emit (node:events:517:28)
  at addChunk (node:internal/streams/readable:335:12)
  at readableAddChunk (node:internal/streams/readable:308:9)
  at Readable.push (node:internal/streams/readable:245:10)
  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**To Reproduce**
I took the liberty to create a simple reproducible nuxt project: https://github.com/20x-dz/builder-vue-test

1. `git clone https://github.com/20x-dz/builder-vue-test`
2. `cd builder-vue-test`
3. `npm ci`
4. `npm run build`

**Expected behavior**
The build for the vercel preset should succeed.

**Additional context**
* Removing the sdk from the recommended `transpile` works (at least the build succeeds), but then the error from #2917 pops up:
`Unknown file extension ".css" for /Users/me/Downloads/builder-vue-test/.output/server/node_modules/@builder.io/sdk-vue/lib/node/style.css`
* While I initially thought that this might be nitro preset related, when setting up the dummy I noticed that this also happens on the default ("node-server") preset.
* This does not happen when [`app.vue` is used instead](https://github.com/BuilderIO/builder/tree/70fa50d604bebad042813d3460805752185736ca/examples/vue/nuxt-3).

**Comment by 20x-dz** [comment]
@samijaber Thank you very much, just saw the release and tested it. 💯 

Transpiling does not seem to be necessary now anymore, is that correct? (This error at least still occurs when transpiling, but neither this nor #2917 happen when transpilation is removed, see https://github.com/20x-dz/builder-vue-test)

**Comment by samijaber** [comment]
Correct. I have added a Nuxt module that you can use to import the CSS correctly. You should also no longer `transpile` the package, as that caused other issues.

See https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/vue#getting-started for instructions
