### ISSUE TITLE
{all : unset} taking higher specificity

### ISSUE THREAD

**Issue by we-surinder-s001** [BuilderIO/builder#2926]
@samijaber When ever I create a button with builder.io the styling on it doesn't work because
{all: 'unset'} property is taking higher specificity.

1. Create a new button with builder.io tool bar.
2. default style will not be applied
3. public the changes.
4. now check in the inspect that the {all: unset} property is already taking higher specificity that the other stylings.

**Expected behavior**
button should have some of its stylings and when ever I do any changes in the styling it should reflect there

**Screenshots**
![image](https://github.com/BuilderIO/builder/assets/155720038/55aba874-a328-4be4-ba6e-68fbc023655b)

**Comment by samijaber** [comment]
Thanks @we-surinder-s001 , we are aware of the bug and looking for a solution.

**Comment by we-surinder-s001** [comment]
@samijaber thanks for replying.

**Comment by wieseljonas** [comment]
Still not working with svelte

**Comment by wieseljonas** [comment]
For now I've implemented it with HTML API on svelte like so

```   
{#if headerHTMLBlock?.data?.html}
      {@html headerHTMLBlock?.data?.html.replace('all:unset', '')}
    {/if}

    {#if isPreviewingHeader}
      <builder-component
        model="price-page-header-block"
        api-key="5a1025ed9ae1451ebd7362f95b4b0486"
      />
    {/if}    {#if headerHTMLBlock?.data?.html}
      {@html headerHTMLBlock?.data?.html.replace('all:unset', '')}
    {/if}

    {#if isPreviewingHeader}
      <builder-component
        model="price-page-header-block"
        api-key="5a1025ed9ae1451ebd7362f95b4b0486"
      />
    {/if}
    ```

**Comment by samijaber** [comment]
@wieseljonas What version of the Svelte SDK are you using? Could you provide the content URL (like https://builder.io/content/:id) to the content in that screenshot?

**Comment by wieseljonas** [comment]
It’s the latest version and big arises only if I add the button

Jonas Wiesel
Associé
+41 79 737 72 17
***@***.***


www.realadvisor.ch <https://realadvisor.ch>
*RealAdvisor SA*
+41 22 775 05 05
Route de Saint-Julien 198
1228 Plan-les-Ouates

**Comment by wieseljonas** [comment]
https://builder.io/content/9d337de407424776a235582e82465612
