### ISSUE TITLE
System.js not available in Builder core

### ISSUE THREAD

**Issue by rojr** [BuilderIO/builder#294]
# Hi Builder.io Team!

Please excuse me if the issue is not up to standard; this will be my first one.

This is all in context of the front end editor, specifically adding Custom JS / CSS
----

I've been following the [Docs on how to import 3rd party libraries](https://www.builder.io/c/docs/guides/libraries) and there are a few discrepancies I've noticed.

For starters, `System` isn't recognised, I understand this is meant to be included from [SystemJS](https://github.com/systemjs/systemjs, I checked the SDK's `package.json`, and `package-lock.json` and there seems to be no mention of the repository.

I figured that the docs might be outdated, so I started poking around in the SDK that gets sent down with Builder pages, and found the `Builder` global object, which similarly has a function called `Builder.import`, which seems like a wrapper function for the `Systemjs` to avoid adding the whole builder code proxy.

So my issue / question is, am I doing something wrong? Or is this an oversight on the missing Systemjs package.

p.s.

Thanks for the tool, enjoying it so far!

**Comment by steve8708** [comment]
Hey @rojr - great catch! Our docs really need to point out that in most cases we load [System.js](https://github.com/systemjs/systemjs), but not all, so how to load it for you if not done already

Good thing our docs are made in Builder - so just went ahead and made that [update](https://www.builder.io/c/docs/guides/libraries) and published :D 

![image](https://user-images.githubusercontent.com/844291/96912642-83bf6180-1457-11eb-86df-452d2b1716da.png)

**Comment by rojr** [comment]
@steve8708 That was quick!

Would it be a good idea to maybe extend this functionality? My particular use case was, trying to add a lightbox library to work with a custom Symbol I created, and I hoped that Builder would handle this dependency. i.e not load it every single time.

What's the reason for not always requiring System.js, or automatically importing it?

Also - one minor detail on the update how ever, the title has a spelling mistake! 

`Preqrequisites` -> `Prerequisites`.

Thanks again for the feedback, I appreciate your help!

**Comment by steve8708** [comment]
oops, thanks for grabbing my typo! Moved a little too quick - now fixed :D 

leaving out by default is purely so ppl can opt in as needed - lot of our customers care a lot of performance and bundle sizes so we try and opt for as fast and lightweight as possible by default, but still flexible 

@rojr which SDK are you using (or more broadly what is your Builder setup / stack)? for some SDKs and use cases like React, you can install a library one time is to have the dependency in your app bundle and pass it down to the react component like in this doc https://www.builder.io/c/docs/react/custom-actions

or, you could always do some optional script loading. e.g. `if (window.System) { .. } else { /* load system */ }`

anyway tho if you can give some more details on your stack and use case I can give some more prescriptive suggestions

**Comment by rojr** [comment]
Ah, I figured that'd be the case.

I'm currently exclusively using the builder fronted, as this current work is for an outside client, so they maintain the deployment, stack etc, and I only create builder pages.

I'll load the libraries conditionally for now, and see if I can integrate it later on. 

Again, thanks a lot for talking your time out to help, it's been greatly appreciated!
