### ISSUE TITLE
Stop making spammy issue posts on GitHub Repos

### ISSUE THREAD

**Issue by tvdeyen** [BuilderIO/builder#3]
Stop making things like https://github.com/AlchemyCMS/alchemy_cms/issues/1621

Reported and blocked.

**Comment by steve8708** [comment]
hey @tvdeyen, I didn't make this post and I'm not affiliated @ylluminate. I'm sad you jumped to reporting/conclusions so quickly. 

@ylluminate reached out to me enthused that my project could integrate with some other open source projects for the benefit of their end users. He was under the impression that all of Builder was free and open source and would be great for collaboration. I sadly explained that the core product is closed source, but I appreciated his enthusiasm and told him I'm open to exploring other business models as well

Anyway, @tvdeyen I hope you will consider un-reporting/blocking this
