### ISSUE TITLE
Ivy Support for Angular

### ISSUE THREAD

**Issue by aresn** [BuilderIO/builder#30]
Do you have any plans to support Ivy engine on angular ? Lack of support for Ivy has been a deal breaker for us.

**Comment by steve8708** [comment]
@ca136 what do you think is required to add Ivy support to @builder.io/angular?

**Comment by ca136** [comment]
I started to look into this here https://github.com/BuilderIO/builder/pull/38. It looks like we'd need to do some more work on how we package the SDK in Angular 9. I'll keep digging when I have some time, but the CLI error messages are not very helpful:

> ERROR in The target entry-point "@builder.io/angular" has missing dependencies:
> - @angular/platform-browser
> - express

**Comment by aresn** [comment]
Any updates or ETA as when this will be available for Angular ? Angular 9 stable has been released with IVY as its default rendering engine.

**Comment by ca136** [comment]
We don't currently have an ETA, it took a while for Angular 9 to be released and have some other high priority projects taking up most of our time right now. We happily accept contributions so if someone wanted to take a stab at updating the SDK to support v9 then we'd happily accept it!

**Comment by ca136** [comment]
@aresn if you are still interested in testing out Builder, it looks like the cli compiler in angular 9.1 now supports Builder. Let us know if you run into any issues.

**Comment by aresn** [comment]
Thanks @ca136. Will definitely take a look at it in next few days.
