### ISSUE TITLE
`@builder.io/sdk-react-native` fails to render due to rendering a `div` in `DynamicRenderer`

### ISSUE THREAD

**Issue by mikehuebner** [BuilderIO/builder#3005]
**Describe the bug**
Hey all, I found this issue with the latest 1.0.0 SDK on React Native. I can't put a repo together just this second as I'm stepping out for the day but wanted to bring it to your attention!

```
 Invariant Violation: View config getter callback for component `div` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in div (created by DynamicRenderer)
    in DynamicRenderer (created by Columns)
    in RCTView (created by View)
    in View (created by Columns)
    in Columns (created by ComponentRef)
    in ComponentRef (created by Block)
    in RCTView (created by View)
    in View (created by DynamicRenderer)
    in DynamicRenderer (created by BlockWrapper)
    in BlockWrapper (created by Block)
    in Block (created by Blocks)
    in RCTScrollContentView (created by ScrollView)
```

Going through the trace, it just seems to be a `div` getting rendered here which I'm not sure where that could be linked to. Whether mitosis isn't producing the right output or something else. I wasn't seeing this issue on `0.12.3`.

https://github.com/BuilderIO/builder/blob/main/packages/sdks/src/blocks/columns/columns.lite.tsx

**To Reproduce**
1. Render any `column` via Blocks with React Native
2. Call `<Content />` via the RN SDK

**Screenshots**
![CleanShot 2024-02-10 at 18 36 42@2x](https://github.com/BuilderIO/builder/assets/6125123/87f9d387-d11e-42ca-aaf6-9d398b67db43)

**Additional context**
Will update with repo if needed tomorrow! Let me know if I can provide any other details. Will also try to remove the div in favor of whatever the default output is for mitosis and make sure that fixes it. Thanks!

**Comment by mikehuebner** [comment]
The React Native example seems to produce the same results, let me know if I need to create a repo for it since I'm having the same.

**Comment by mikehuebner** [comment]
- `0.12.3` Renders the view fine, none of the buttons work or general interactions but it does display ![image](https://github.com/BuilderIO/builder/assets/6125123/8e91aaa3-894f-440d-93d4-96c66e2ea5a6)

- `1.0.0` does not render and complains of the same error I was getting above, just a different tag ![image](https://github.com/BuilderIO/builder/assets/6125123/129b71c7-f8c9-4cad-abe8-a7439abdbce6)

I made a smaller repo here using latest SDKs: https://github.com/mikehuebner/builderio-react-native-bug-repo

**Comment by mikehuebner** [comment]
Got it rendering by add `linkComponent`, however I don't think this will solve for the issue for when there is a `div` present.

```
<Content
            apiKey={BUILDER_API_KEY}
            model="page"
            content={content}
            linkComponent={Pressable}
            customComponents={CUSTOM_COMPONENTS}
          />
```

**Comment by mikehuebner** [comment]
From reading the types the found..

```
linkComponent={Pressable}
contentWrapper={Stack}
blocksWrapper={Stack}
```

None of these work besides `linkComponent` which makes sense from the code: `TagName={column.link ? props.builderLinkComponent || 'a' : 'div'}`

**Comment by mikehuebner** [comment]
I've got it down to just being how `DynamicRenderer` handles `'div'` and `tagName`. I'm assuming mitosis handles this if it was rendered as an element and not a string that is dynamically rendered. I'm not sure how y'all would want to handle a scenario like this. I could help by putting in a PR that treats these divs like it does `linkComponent`. That way any element could be used as the wrapper.

**Comment by samijaber** [comment]
@mikehuebner Thank you for this helpful issue and explanation. We have received similar reports and are actively working on a fix.

**Comment by samijaber** [comment]
@mikehuebner This should be fixed in https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-react-native%401.0.1

**Comment by mikehuebner** [comment]
Thank you!
