### ISSUE TITLE
How to give just simple array as prop

### ISSUE THREAD

**Issue by Ischafak** [BuilderIO/builder#3006]
**Describe the bug**
Hi, first of all i am using nuxt. it is not a bug but i have an image array something like this

['imagepath1''imagepath2']

i want props in this format but when i select 'list' type it forces me to make array object.
Cant i make just an array which users can selects multiple images from editor?

**Screenshots**
<img width="487" alt="image" src="https://github.com/BuilderIO/builder/assets/13226879/ba12117f-796f-4ad9-b48d-5a5e7aa68d24">

<img width="380" alt="image" src="https://github.com/BuilderIO/builder/assets/13226879/530035b5-30e3-40f9-b8e2-fc395b4c79b7">

**Comment by Ischafak** [comment]
must i do 
[
  {
  image: 'imagepath1'
  },
  {
  image: 'imagepath2'
  },
]

something like this

**Comment by mrkoreye** [comment]
@Ischafak yes, you are correct, it will be a list in that format if you want to have the input be of image type. For more information on input types, please see this documentation: https://www.builder.io/c/docs/custom-components-input-types
