### ISSUE TITLE
Types broke  in Vue SDK after 0.12.8

### ISSUE THREAD

**Issue by fazulk** [BuilderIO/builder#3008]
**Describe the bug**

**To Reproduce**
1. Install anything after 0.12.8
2. Check types in your IDE (in this case vscode)
3. No declaration file found

![image](https://github.com/BuilderIO/builder/assets/21964900/1e696105-ba77-4b0b-a58a-636bb66802ee)

**Additional context**
Worked fine in 0.12.8 and prior versions

**Comment by samijaber** [comment]
v0.13.0 actually includes fixes to the Vue SDK types. Not sure why you're seeing this instead. It might be something to do with your specific TS config?

You might want to compare your repo with the example at https://github.com/BuilderIO/builder/blob/main/examples/vue/vue-3/src/App.vue, which works when updated to v1.0.0

![CleanShot 2024-02-14 at 12 58 25@2x](https://github.com/BuilderIO/builder/assets/1393142/66c70a61-6e75-4c3e-af0a-29d250f199a2)

**Comment by samijaber** [comment]
You also need to use the following VSCode extension to get types in Vue 3:

```
Name: Vue Language Features (Volar)
Id: Vue.volar
Description: Language support for Vue 3
Version: 1.8.27
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar
```

**Comment by fazulk** [comment]
on tsconfig i had this set 

`"moduleResolution": "Bundler"`

which i figured was best because that is what vite is doing. 

Setting it back to 

`"moduleResolution": "Node"`

got rid of the TS errors. Thx!
