### ISSUE TITLE
see image preview instead cloud icon

### ISSUE THREAD

**Issue by Ischafak** [BuilderIO/builder#3017]
![image](https://github.com/BuilderIO/builder/assets/13226879/7910ac2e-ee7c-41f6-878b-c97ee6818b60)

hi, i have an array object which has images for swiper.
The problem is i cant understand which image i am currently editing. there is cloud icon on the left side can i see the image instead of cloud?

**Comment by Rameshk84** [comment]
* Add this code you can resolve the error 

import React, { useState } from 'react';

const SwiperComponent = () => {
  // Assuming you have an array of image URLs
  const images = [
    'image1.jpg',
    'image2.jpg',
    'image3.jpg',
    // Add more image URLs as needed
  ];

  const [selectedImageIndex, setSelectedImageIndex] = useState(0);

  const handleImageClick = (index) => {
    setSelectedImageIndex(index);
  };

  return (
    <div className="swiper-container">
      <div className="swiper-wrapper">
        {images.map((image, index) => (
          <div
            key={index}
            className={`swiper-slide ${index === selectedImageIndex ? 'active' : ''}`}
            onClick={() => handleImageClick(index)}
          >
            {/* Render image preview instead of cloud icon */}
            <img src={image} alt={`Image ${index}`} />
          </div>
        ))}
      </div>
      {/* Add pagination, navigation buttons, etc. if needed */}
    </div>
  );
};

export default SwiperComponent;
