### ISSUE TITLE
Using own React components while fetching page contents in the backend?

### ISSUE THREAD

**Issue by martin-braun** [BuilderIO/builder#302]
First of all, outstanding project. This really has potential, because it provides a solid builder while still giving full control of its implementation. If I understand the documentation right, I cannot use the HTML API when I want to implement my own React components in my builder. I'm really looking forward to jsx-lite, because it will allow to bypass this issue entirely.

Until then, I wonder what I can do, because GDPR will force me to get permission from the user to make a request to your React API in the front-end. Only if I do so, I can hook my own components into your builder, properly.

But now I wonder, what if I call ...

```js
builder.get('page', { url: '/' })
```

... in an express backend and deliver the resulting `pageJson` to the front-end to attach it to the `BuilderComponent`, so that I can avoid the direct call to your server from the front-end? 

Is this possible?

**Comment by mandx** [comment]
Something you can try is hit Builder's APIs directly from your backend and from it return it to your frontend, fetching it during route handling, cache it or whatever is needed, then return it as part of the response to the frontend. Then in your frontend:

```javascript
import { BuilderPage } from '@builder.io/react';

export default function Homepage({ builderContentFromMyApi, ...props }) {
  return <div>
    <p>some static content... </p>
    <BuilderPage content={builderContentFromMyApi} />
    <p>more static content</p>
  </div>
}
```
You might also have to apply some of the advice [here](https://forum.builder.io/t/gdpr-compliance/292/3) to ensure the Builder SDK is GDPR compliant.

**Comment by martin-braun** [comment]
Thank you, I will give it a try, soon. 👍

**Comment by mandx** [comment]
@martin-braun My comment  in the snippet I shared: First, its `BuilderComponent` (not `BuilderPage`), and you need to add the `model` prop to `BuilderPage`, like:

```javascript
    <BuilderPage content={builderContentFromMyApi} model={contentModel} />
```
Where content model could be `'page'` (the initial model you get when you start using Builder), or whatever model name you are using to fetch content (the first argument you used when calling `builder.get()`.

I'll edit my initial comment to avoid confusion

Thanks to @teleaziz for catching this!
