### ISSUE TITLE
sdk-react gen2 useContext

### ISSUE THREAD

**Issue by woellij** [BuilderIO/builder#3044]
Hi there, thanks for the great Product you're making here.

I'm trying to migrate a project from gen1 SDK to gen2 SDK but facing the issue that there is no documented way to access any `BuilderContext` like it was in gen1.

In Gen 1 i could access the `BuilderStoreContext` through react.useContext, which does not seem to be possible in gen2.

I've looked through the compiled sources and exported types and there does not seem to be a way. 

Is this on the roadmap to add / document?

Thanks in advance.

**Comment by woellij** [comment]
Hi. Just following up. We'd like to use the GEN2 SDKs but there is no way to update the `BuilderStoreContext` with a new state. Could you enlighten us please?

**Comment by mrkoreye** [comment]
Hi @woellij , can you describe what you are trying to achieve in more detail so that we can help? As in, what is the end goal you have? Are you trying to pass functions to be used within Builder content? Set an initial state for Builder content?

**Comment by woellij** [comment]
Hi @mrkoreye ,
The Goal is to Update the state from a custom component. 
Im our case there is a custom component in which the User can select a product which should cause an update to the state, so text on the page can jind to the product's properties. 
We have other uses for the state and context (passing state and context props to child components)

**Comment by woellij** [comment]
Hi. 
I had a look and while i can reference the `BuilderContext` in `useContext`, there is no real typescript type information and one would have to resort to the builder.io sourcecode to find out about `BuilderContextInterface`.
In my opinion that's not really optimal.
