### ISSUE TITLE
React list error

### ISSUE THREAD

**Issue by MaximeGratens** [BuilderIO/builder#3082]
Hello,

Using React sk2 with remix js, we are getting react error by using your select.

The error :
`react.development.js:209 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `nn`. See https://reactjs.org/link/warning-keys for more information.
    at option`

A key is missing on the option map

**Comment by mrkoreye** [comment]
Thank you @MaximeGratens for letting us know! We will let you know when we have a fix for this.

**Comment by samijaber** [comment]
This was fixed in https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/react/CHANGELOG.md#1020
