### ISSUE TITLE
Using Next.js App Dir with Builder V2

### ISSUE THREAD

**Issue by RobSchilderr** [BuilderIO/builder#3235]
**Describe the bug**
In [this example](https://github.com/BuilderIO/builder/blob/main/examples/nextjs-app-dir-v2/src/app/%5B%5B...slug%5D%5D/page.tsx), provided by Builder.io, it is suggested to use the following code snippet:

```
  const { initializeNodeRuntime } = await import('@builder.io/sdk-react/node/init');
  initializeNodeRuntime();
``` 

However, initializeNodeRuntime does not seem to exist within the module, as evidenced by the following error screenshot:

<img width="713" alt="Screenshot 2024-04-24 at 13 06 51" src="https://github.com/BuilderIO/builder/assets/35261620/92cb9784-c30e-4240-b9a6-b24806d2e38a">

This issue occurs despite following the recommended setup. I would prefer to use this package due to its compatibility with the pages router in my project, which precludes using the [Next.js SDK](https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/nextjs). 

Additionally, I attempted to use the directive 'use client' at the top of the file to handle client-side custom components, but this approach failed to resolve the issue.

**To Reproduce**
1. Initialize a new Next.js project (version 13.4.8) configured with the app router.
2. Attempt to import initializeNodeRuntime as specified.
3. Observe the error indicating that initializeNodeRuntime cannot be found.

**Expected behavior**
- Being able to use App Router and Pages Router with Builder V2
- Being able to register components, only client side components is okay.

**Additional context**

Using Next.js version 13.4.8 and following the guide provided in the Builder.io GitHub repository.

**Comment by khiemtong** [comment]
We ran into this (we're on NextJS 14.1) following the same instructions, the workaround is to manually declare the module (it is there in the package just not declared?)

Add something like `decs.d.ts` to your root 

```Typescrilpt
declare module '@builder.io/sdk-react/node/init';
```

**Comment by samijaber** [comment]
Yes, there is an issue with the types not propagating correctly for certain TS configurations. We will investigate this, thanks for reporting.

The import itself should work correctly on the JS side.

**Comment by jaydubb12** [comment]
@samijaber   @omspacecode this bug appears to be stale, and I have observed that the omission of the `vm-runtime` config does not prevent me from using the dependency.  I also noted some changes to the dependencies specific to this feature in latter releases....

Thoughts?

**Comment by samijaber** [comment]
@jaydubb12 the `initializeNodeRuntime` function is only needed for certain production Node.js environments (such as Vercel) which tend to apply additional bundling steps that may remove sub-dependencies from the server bundle (such as `isolated-vm` in this case).

If your production environment is not running into any errors, then this means it does not need `initializeNodeRuntime` and you are free to ignore it.

**Comment by jaydubb12** [comment]
@samijaber good to hear.  The challenge is, we need to be able to build it locally...and that is currently the challenge I have also run into.

The issue appears to be a file resolution problem during build time.

**Comment by samijaber** [comment]
@jaydubb12 I am not following. What issue are you encountering exactly? Please provide a detailed breakdown with error logs and how you've integrated the SDK. 

If your issue is unrelated to the one discussed here, please open a separate Github Issue to track it.

**Comment by samijaber** [comment]
Closing this issue as the types declaration problem has been fixed already.
