### ISSUE TITLE
Image override with the Cloudinary plugin

### ISSUE THREAD

**Issue by donnieblando** [BuilderIO/builder#33]
When more than one image is added to the page through the Cloudinary plugin, the last one to be added **overrides all the other ones**

**Comment by steve8708** [comment]
this is most likely in the plugin code from Jacob - pinged him to see if he can take a peek, can look on our end too if it looks to him like the source of the issue is on our / the platform side (rather than the plugin)

**Comment by ca136** [comment]
Thanks for sending https://github.com/BuilderIO/builder/pull/35 @donnieblando!

**Comment by steve8708** [comment]
Fixed via #35 👍
