### ISSUE TITLE
Node 22 compatibility

### ISSUE THREAD

**Issue by timothybonci** [BuilderIO/builder#3307]
**Describe the bug**
Node 22 introduced a major version bump in V8, which required updates in packages using V8 directly.  isolated-vm released a version 5.0.0, I'm assuming to deal with the breaking changes, but the dependency we have, @builder.io/react, depends on isolated-vm ^4.5.0, so we can't run on Node 22 yet.  I'm not sure if any of the interfaces changed in isolated-vm - I just wanted to call out that we would like to install our project on a Node 22 based-image and can't right now.

**To Reproduce**
1. Check out a project using @builder.io/react onto a Node 22 image (we used node:22.2.0-alpine3.18)
2. npm i -> install blows up with V8 errors

**Expected behavior**
Removing our package-lock and updating dependencies should allow us to build/install the project.

**Comment by manucorporat** [comment]
Should be fixed now by https://github.com/BuilderIO/builder/pull/3343
