### ISSUE TITLE
Request to switch Solid SDK dependency solid-styled-components with solid-styled

### ISSUE THREAD

**Issue by davedbase** [BuilderIO/builder#3314]
I'd like to formally submit a request to switch `solid-styled-components` with `solid-styled`. The previous package is mostly deprecated and depends on Goober which doesn't support SSR well (the result is a lot of terrible CLS). solid-styled [supports SSR rendering](https://github.com/lxsmnsyc/solid-styled/tree/main?tab=readme-ov-file#ssr) without Goober.

This would fix a number of issues with the Solid SDK and make it far more useable in production.

**Comment by samijaber** [comment]
This has been fixed in 1.0.33, where the styles are now inlined `<style>` tags. https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/solid/CHANGELOG.md#1035
