### ISSUE TITLE
Problem with save template and use template

### ISSUE THREAD

**Issue by anhtuanlee** [BuilderIO/builder#3327]
version: 
 "@builder.io/react": "^3.2.6",
 "@builder.io/sdk": "^2.2.2",
 "@builder.io/dev-tools": "^1.0.8",

I Have a problem with save template, when i use template in show default will not work, and this will show like components 
![image](https://github.com/BuilderIO/builder/assets/105347995/9b12b3a0-68c1-4b11-a8f8-1ae9b842df1b)
![image](https://github.com/BuilderIO/builder/assets/105347995/e2125a0c-7c97-45bc-9767-3c9ea5c0849d) 
 
And i found a solutions, if i  open button view all template 
![image](https://github.com/BuilderIO/builder/assets/105347995/b9158610-b540-49d6-8e0e-c1c449e65871)

And choose this template will work 

(This is result) 
![image](https://github.com/BuilderIO/builder/assets/105347995/2d6862c1-4f8f-4e96-b48b-a4d75f7d2f84)
 
IDK what i wrong or builder have prolem,  i think have bug in FE, incorrect when select, type of template is a component

Tks so much!!!

**Comment by maximun0805** [comment]
That right, I have the same issue, i can't find solution so my boss scolded me :((

**Comment by anhtuanlee** [comment]
> That right, I have the same issue, i can't find solution so my boss scolded me :((

U can use  my solution, click button my all template,  will resolve prolem

**Comment by maximun0805** [comment]
OMG !! you save my life 👍
