### ISSUE TITLE
How to work completely offline

### ISSUE THREAD

**Issue by linonetwo** [BuilderIO/builder#336]
Hi, this is an awesome low-code project, I found it very inspiring.

A thing I not sure about is that, Is it possible to make the low-code editor and the SDK work both offline? 

I'd like to add a low-code editor to https://github.com/Jermolene/TiddlyWiki5 (A privacy first, totally offline, sync-to-GitHub personal knowledge base)
Then users can compose powerful mini-app in their wiki, just like Coda and Notion works.

Seems currently the low-code editor is not opensource (I think this is ok, because you need user growth in your service), but maybe I can just create my own low-code editor, and provide the JSON to the SDK?
And maybe I should use BuilderIO/jsx-lite directly instead of BuilderIO/builder, because TiddlyWiki doesn't use React...I can't use @builder.io/react

**Comment by steve8708** [comment]
Hey @linonetwo - you are absolutely right, you can use Builder offline by supplying the JSON to it directly, e.g. `<BuilderComponent content={...} />`

where `content` has the structure:

```ts
{
  data: {
    blocks: [
       { '@type': '@builder.io/sdk:Element', component: { name: 'MyComponent', options: { /* the props */ } } }
    ]
  }
}

```

you can examine the JSON by right clicking any content in our visual editor (e.g. over at builder.io/fiddle) and choosing "download as JSON" you can peek the json. also from the data tab you can see the json for any selected block by clicking the "json" button at the bottom 

you can also see the type definitions for the top level [content object](https://github.com/BuilderIO/builder/blob/master/packages/core/src/types/content.ts#L17:L17) and the [blocks](https://github.com/BuilderIO/builder/blob/master/packages/core/src/types/element.ts#L10:L10)

**Comment by linonetwo** [comment]
Thanks, this is interesting. I like your schema, it looks like JSON-LD, have a feeling of RDF.
