### ISSUE TITLE
Vue sdk is not exporting trackConversion or builder

### ISSUE THREAD

**Issue by ps-20x** [BuilderIO/builder#3469]
**Describe the bug**
The vue sdk is not exporting `trackConversion` or `builder` for `builder.trackConversion()` to be able to track conversions in vue.

**To Reproduce**
1. Create a vue project
2. Install `@builder.io/sdk-vue`
3. No import for `trackConversion` or `builder` possible

**Expected behavior**
An export is added in the sdk

**Additional context**
Posted a question in the forum already but there is no reply: https://forum.builder.io/t/trackconversion-in-vue-nuxt/6074

**Comment by samijaber** [comment]
Closing since, as per the forum discussion, this SDK exports `track` (the exports described in this issue are only relevant to another unrelated SDK)
