### ISSUE TITLE
Can't login to builder.io with github

### ISSUE THREAD

**Issue by badgifter** [BuilderIO/builder#3561]
**Describe the bug**
Tried to login with github, but I get this error.

"The redirect_uri is not associated with this application"

**To Reproduce**
1. Go to builder.io
2. click sign up
3. click github to login
4. error

**Expected behavior**
Log in...

**Screenshots**
![image](https://github.com/user-attachments/assets/85a06082-6936-4592-88a7-69abece93c16)

**Comment by kylefowler** [comment]
Should be resolved. Let us know if you hit any issues again
