### ISSUE TITLE
Nuxt3 - isolated-vm build issue

### ISSUE THREAD

**Issue by 20x-dz** [BuilderIO/builder#3604]
**Describe the bug**
Following the latest release ([sdk-vue@v2.0.17](https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%402.0.17)) with #3560, I immediately installed the latest version to see if #3288 was indeed fixed.

Unfortunately, the manual way of loading it does not work as it fails already on the build step:

```
Running "npm run build"

> build
> nuxt build

[log] Nuxt 3.13.0 with Nitro 2.9.7
[info] [nuxt:tailwindcss] Using Tailwind CSS from ~/assets/css/tailwind.css
[info] Building client...
[info] vite v5.4.7 building for production...
[info] ✓ 315 modules transformed.
[error] x Build failed in 2.11s
[error] Nuxt Build Error: Could not resolve "./out/isolated_vm" from "./out/isolated_vm?commonjs-external"
file: ./out/isolated_vm?commonjs-external
  file: ./out/isolated_vm?commonjs-external
  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (node_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:19273:24)
  at node_modules/rollup/dist/es/shared/node-entry.js:19233:26
Error: Command "npm run build" exited with 1
```

**To Reproduce**
1. get a fresh/empty nuxt 3 project up and running
2. make the necessary builder adjustments as per the official documentation
3. adjust
```
<!-- pages/[...app].vue -->
<script setup>
  // ...

  if (process.server || import.meta.server) {
    const { initializeNodeRuntime } = await import('@builder.io/sdk-vue/node/init');
    initializeNodeRuntime(); // initializes Isolated VM in the server
  }

  // fetch builder data after
</script>
```
5. run `npm run build`

**Expected behavior**
A successful build.

**Additional context**
I ran across this issue in my GitHub CI/CD pipeline that we're using to deploy to vercel. But I was able to confirm the build issue is not related to it being run in the pipeline or vercel related as it happens with a normal `npm run build` as well.

**Comment by samijaber** [comment]
Thanks for the quick followup @20x-dz .

it looks like that suggestion from our docs is not entirely accurate. We will remove that suggestion from the docs. Thanks for catching that.

In the meantime, the recommended approach is to enable the `initializeNodeRuntime` config in our nuxt module. It takes care of initializing the runtime for you.

```ts
export default defineNuxtConfig({
  modules: [["@builder.io/sdk-vue/nuxt", { initializeNodeRuntime: true }]],
});
``` 

Can you let me know if that works on your codebase? I just tested it successfully on my end on a new nuxt3 project

**Comment by samijaber** [comment]
I see that you followed this step in https://github.com/BuilderIO/builder/issues/3605. Can you confirm that the module approach does work for you?

**Comment by 20x-dz** [comment]
@samijaber yes, the module approach works, the build finishes successfully.

**Comment by samijaber** [comment]
Excellent. We have rectified the changelog in https://github.com/BuilderIO/builder/pull/3606 to address this.

Thanks again!
