### ISSUE TITLE
bundle size is too large, how to tree shake `builder-react`?

### ISSUE THREAD

**Issue by xieyezi** [BuilderIO/builder#3652]
**Describe the bug**
I used the following packages and integrated them into Next.js, but I found that the bundle size is too large, affecting my initial page load speed.

```json
    "@builder.io/dev-tools": "^1.0.16",
    "@builder.io/react": "^3.2.7",
    "@builder.io/sdk": "^2.2.3",
    "next": "^14.2.4",
```

**To Reproduce**
<img width="898" alt="image" src="https://github.com/user-attachments/assets/e80f4f50-c126-488b-90bd-0c02a9a9fe39">

**Expected behavior**

Is it possible to tree shake `builder-react`?

**Comment by steve8708** [comment]
hey @xieyezi - try out the gen2 react SDK, it's much more tree shakeable

**Comment by samijaber** [comment]
If you are concerned about bundle size, we encourage you to explore our React Gen2 SDK: it is substantially smaller (currently at `26Kb` gzipped, see [bundle analysis](https://bundlejs.com/?q=%40builder.io%2Fsdk-react&treeshake=%5B%7BContent%2CfetchOneEntry%7D%5D&config=%7B%22esbuild%22%3A%7B%22external%22%3A%5B%22react%22%2C%22react-dom%22%5D%7D%7D)) ![badge](https://edge.bundlejs.com/?q=%40builder.io%2Fsdk-react&treeshake=%5B%7BContent%2CfetchOneEntry%7D%5D&config=%7B%22analysis%22%3A%22treemap%22%2C%22esbuild%22%3A%7B%22external%22%3A%5B%22react%22%2C%22react-dom%22%5D%7D%7D&badge=detailed)

You can find information on how to use Gen2 SDK in our docs: https://www.builder.io/c/docs/integrating-builder-pages#add-builder-as-a-dependency

by selecting `Gen 2` from our `SDK Generation` dropdown above any of the code snippets

**Comment by xieyezi** [comment]
@samijaber I tried using `@builder.io/sdk-react` based on the recommendation, but I encountered some difficulties with the documentation. For instance, the videos or instructions for SDK2 still use examples from SDK1. If I may ask, could you please let me know when SDK2 is expected to be officially released? Thank you!
