### ISSUE TITLE
CLI issues on Windows

### ISSUE THREAD

**Issue by k-schneider** [BuilderIO/builder#3768]
**Describe the bug**
When running builder.io CLI commands from a Windows command line (or Powershell) it prompts you to open a file instead of executing.

**To Reproduce**
1. Run `npx builder.io figma publish` from a Windows command line
2. Observe that it prompts you to open a ".io" file
3. The contents of the file is a bash script:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@builder.io/dev-tools/cli/main.cjs" "$@"
else 
  exec node  "$basedir/../@builder.io/dev-tools/cli/main.cjs" "$@"
fi
```

**Expected behavior**
The command executes as expected.

**Comment by kylefowler** [comment]
We are taking a look at this, in the interim, `npx @builder.io/dev-tools figma publish` should work

**Comment by kylefowler** [comment]
Going to mark this one as closed for now. We have updated all references to `npx builder.io` in our products for Windows users. We will change it back once the npm issue is resolved, but until then commands the product tells you to do on Windows should be functional.
