### ISSUE TITLE
Scope of the opensource project

### ISSUE THREAD

**Issue by axyz** [BuilderIO/builder#379]
Hi, 
I'm considering different projects to be used for visual editing (mostly for prototyping, but content management could be considered later on).

First of all I want to compliment for the quality of this project, for what I've seen so far it has one of the best usability and integrations capabilities among other open source competitors.

Can you clarify what are the boundaries between this project and the builder.io services?

Is it possible to use this project without an API token? Is there any documentation about that and, eventually, specifications to follow to build a custom API for it? Is it possible to isolate a lightweight version of the editor? (I would mostly be interested on the visual editor, custom components and possibility to import/export/load JSON to reproduce the designs, may not need most of the managed features like roles and similar)

I'm not sure how much that would clash with the current business model, my assumption is that it is in your interest that the open-source part gets stronger so that there will be more demand for a paid managed offer. I imagine this project as possible competitor to gutenberg, tinacms, editorjs, blocks-ui, etc... with a strong focus on allowing the creation of complete design system specifications without injecting necessarily default components and/or styles.

As a side not would be interesting to evaluate how complex would be to have an integration layer to use gutenberg components, as they are react based and used similar js object to define the editor behaviors, I do not have this need now, but it seem like an opportunity given the huge amount of components available for it and large developers base due to wordpress.

I am also very interested on having strong control over layouts: Is it possible to specify allowed children/siblings per component (like in gutenberg)? Is it possible to create custom layout component, like a custom type of grid, that can have customized options and templates (like 50/50, 33/33/33, etc...)? Is it possible to customize style options like padding and margins to be limited to a set of fixed allowed values and map them to custom css classes?

While so far I found gutenberg to be one of the most mature options, is also not extremely easy (kind of possible, but not officially supported/documented) to use it without wordpress, and get rid of some default components and styles that could clash with a custom design system, also component creation is very flexible, but also a bit cumbersome and requires lot of additional work from an existing react component to a usable element in the editor.

Sorry if the order and the amount of questions is a chaotic, I'll be happy to clarify further my use case if needed.
Thanks

**Comment by steve8708** [comment]
No problem - hope this helps:

> Can you clarify what are the boundaries between this project and the builder.io services?

Absolutely, in short what is open source:

- The data format for Builder - aka an open JSON format for describing applications (composed of components) as pure JSON and rendering them with our SDKs
- SDKs - all of the things that render out this content, that you can use with our without the backend platform
- Plugins - plugins to the Builder platform for adding features around content creation, editing, and management
- Examples - lots of examples of using Builder for different use cases and platforms

What is closed source but free:
- Our drag and drop editor. You can use it for free at buidler.io/fiddle (or with a free account) and download the content as JSON (for passing to SDKs) or as generated code via JSX Lite

What is closed source and paid:
- Our APIs - aka the ability to add multiple users to an account, generate content, and click to publish it dynamically served to your web and mobile applications

> Is it possible to use this project without an API token? 

It is, so one thing for example you can do is make content in our fiddle (buidler.io/fiddle), right click and choose "download as json" and then pass that JSON to an SDK. e.g.

```jsx
let json = { ... } // the json you downloaded

return <BuilderComponent content={json} />
```

> Is there any documentation about that and, eventually, specifications to follow to build a custom API for it?

Given the data is just JSON, you can do this however you want. Grab it from the editor and put in any DB, pass through any API, etc. 

You can also use [webhooks](https://www.builder.io/c/docs/webhooks) with free or low cost tiers of our platform to automate this

> Is it possible to isolate a lightweight version of the editor?

Right now you can't self host the editor, but what you can do is create one based on the data model we use. Some more info about that [over here](https://github.com/BuilderIO/builder/issues/336)

> As a side not would be interesting to evaluate how complex would be to have an integration layer to use gutenberg components, as they are react based and used similar js object to define the editor behaviors, I do not have this need now, but it seem like an opportunity given the huge amount of components available for it and large developers base due to wordpress.

Totally, you can tag any React component for use in Builder, [this doc](https://www.builder.io/c/docs/custom-react-components) explains more

> I am also very interested on having strong control over layouts: Is it possible to specify allowed children/siblings per component (like in gutenberg)? Is it possible to create custom layout component, like a custom type of grid, that can have customized options and templates (like 50/50, 33/33/33, etc...)? Is it possible to customize style options like padding and margins to be limited to a set of fixed allowed values and map them to custom css classes?

100% is. Check out our [components-only mode](https://www.builder.io/c/docs/guides/components-only-mode) and info [here](https://www.builder.io/c/docs/custom-react-components#template-button:~:text=with-,childRequirements) on how to specify requirements for child components.

You can absolutely create custom layout components (also note our built in components are open source so you can edit those or create new ones using those as inspiration).
[This example](https://github.com/BuilderIO/builder/tree/master/examples/react-design-system) is a whole kitchen sink of how you can structure and set limitations on component usage in Builder. 

To change the design/editor options (like specific subset of style values that link to different things like classes) you can create custom [plugins](https://www.builder.io/c/docs/extending/plugins) for that
