### ISSUE TITLE
Querying record using boolean userAttributes is not working

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#39]
When I trying to query record from builder.io I getting empty array when I use `boolean` value for in query params. I've already tried to pass `true`, `false`, `1`, `0` but without success.

It started to work when I changed the type of targeting variable  from `boolean` to `string`

Settings used in builder.io:
![image](https://user-images.githubusercontent.com/22659410/72348548-f20e1100-36da-11ea-8ce5-d1b16306d242.png)

And here you have params passed to builder CDN:
```
userAttributes.urlPath: /
userAttributes.host: localhost:5000
userAttributes.device: desktop
userAttributes.env: dev
userAttributes.loggedIn: false **(i've tried also 0)**
prerender: true
cacheSeconds: 5
options.page:/.prerender: true
options.page:/.model: "page"
options.page:/.static: false
```
Response:
![image](https://user-images.githubusercontent.com/22659410/72349052-11f20480-36dc-11ea-8b48-61a9c8fd3375.png)

Builder.io entry ID: `0434387fe28c48fc833979640008d033`

@ca136 @steve8708  Can you take a look at it on builder.io server-side app?

**Comment by steve8708** [comment]
Fixed - thanks for the detailed report @lyczos !
