### ISSUE TITLE
Install builder.io on 1mb.site

### ISSUE THREAD

**Issue by carlospg93git** [BuilderIO/builder#4]
Hi! 

I am pretty new to this kind of tools and I don't know how to code. I love builder.io because it is super easy to get things done but I am having trouble when trying to "install" the page I have created in my website (1mb.site). 

I would like to do it in the simplest form (Don't use React nor Vanilla ....). I just want a code snippet in HTML with the things I have to change to show the page I have created in my page in 1mb.site. Could it be possible to have a video tutorial? It would be very useful.

Thanks in advance and congratulations for the hard work!!

**Comment by steve8708** [comment]
Hey Carlos,

Thank you for your kind words! To show content you made in Builder on your 1mb.site you will want to use the [HTML API](https://builder.io/c/docs/html-api).

I would recommend following the guide [here](https://builder.io/c/docs/getting-started) using the "Vanilla JS" tabs. By "Vanilla JS" I just mean plain JS - aka no framework, so will work for any website

You can also see a full working example in plain (no framework) JS here https://codesandbox.io/s/github/BuilderIO/builder/tree/master/examples/plain-js

Let me know if this helps or if you have any other questions at all just let me know!

**Comment by carlospg93git** [comment]
Thanks!! I finally made it. Thank you for your help 😄

**Comment by steve8708** [comment]
Great, anytime!
