### ISSUE TITLE
[Feature request] Possibility to mark targeting variables as required for given models

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#40]
I need this kind of feature to create separate version of pages for each env.
Right now I am using `Custom Targeting Attributes` but some times when I forgot to select a value for this targeting attribute page will be visible across all environments.
![image](https://user-images.githubusercontent.com/22659410/72508328-c9565a80-3845-11ea-9002-53089c41aee0.png)

![image](https://user-images.githubusercontent.com/22659410/72508051-4b924f00-3845-11ea-8e55-01a604ccdb3e.png)

Can we add some kind of REQUIRED FOR: (models/models types?)

Or maybe I should use page options for it instead of targeting attrs? 
![image](https://user-images.githubusercontent.com/22659410/72508283-ba6fa800-3845-11ea-9c28-a7f9feda6138.png)

What do you think @steve8708 @ca136 ?

**Comment by ca136** [comment]
That makes sense, I can add a "required" checkbox in the custom targeting attribute creation screen. That way you'll see an error in the editor when trying to publish without setting the targeting attribute. Would that solve the issue you're running into?

**Comment by lyczos** [comment]
I think yes @ca136 :)

**Comment by steve8708** [comment]
added and deployed to `beta.builder.io` - if you go to beta.builder.io/models and choose a model, and choose "show advanced" under the model options, there is a button to set required targets. Choose what needs to be required and then it will warn and disallow publishing for any content of that type that does not set a value for those targets

will go out to builder.io production next week

as always thanks for the detailed feedback @lyczos !
