### ISSUE TITLE
is it possible to use the starters written in typescript for normal react, next and gatsby?

### ISSUE THREAD

**Issue by creativemacmac** [BuilderIO/builder#408]
hey there guys :)

I was wondering if it's possible to use the starters written in typescript for normal react, next and gatsby? Or do I need something else?

**Comment by teleaziz** [comment]
Hi @creativemacmac, please elaborate, I'm not sure I got your question right.

**Comment by creativemacmac** [comment]
Sorry for the delayed response :) I had a browse through the nextjs starters...are they written in typescript? I am wondering if I can use the typescript starter for nextjs without actually writing my full project in typescript? I cannot quite seem to find a nextjs starter wh

**Comment by mandx** [comment]
Well Typescript is supposed to be a superset of Javascript, so you should be able to just clone the starter and convert it from a Typescript project to a Javascript project:

- Rename all code file extensions from `.ts` and `.tsx` to `.js` and `.jsx`
- Remove any Typescript related dependency (like `typescript` and any dependency with the `@types/` prefix
- Adjust the `scripts` section of `package.json` accordingly; like adjusting extension patterns (`src/**/*.{ts,tsx}` -> `src/**/*.{js,jsx}`), remove/replace references to the `tsc` compiler, etc.

Alternatively you could start a regular empty React/Netx/Gatsby project using only plain Javascript and use the starter code as a reference of what to add/configure, If you need to copy/paste code, simply remove the types bits and it should work.

Does this helps?

**Comment by creativemacmac** [comment]
yes that's perfect thanks :)
