### ISSUE TITLE
Javascript href value is interpreted as relative link by @builderio/angular

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#42]
When in angular component I will have a link like:
`<a href="javascript:void(0);"></a>`
and I will use this component in Builder.io  then @builderio/angular will try to use an Angular router to navigate, so it will throw 404.

It is caused by `packages/angular/src/app/modules/builder/components/builder-component/builder-component.component.ts` `onClick()`

**Comment by steve8708** [comment]
@lyczos try out `@builder.io/angular@1.0.78-alpha.6` I believe that should have this issue fixed
