### ISSUE TITLE
How to run builder editor locally?

### ISSUE THREAD

**Issue by ffleandro** [BuilderIO/builder#429]
I can't find any details about how to run builder editor locally on my development environment.

**Comment by ffleandro** [comment]
Could someone provide some simple details on how to run builder locally?

**Comment by teleaziz** [comment]
Hi @ffleandro , the editor is outside the scope of this project, please take a look at [this issue](https://github.com/BuilderIO/builder/issues/379#issuecomment-780033454) for more details on what's included here and is open-source.
