### ISSUE TITLE
Filtering issue on builder.io

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#43]
When I want to filter records using ENUM values it is not possible to select multiple values or when some record has multiple values (ex. "Env: `demo`, `dev`" ) record is not showing when I select `demo` 
![image](https://user-images.githubusercontent.com/22659410/72627248-6ef3f180-394c-11ea-9880-aa9d1ecc9195.png)

**Comment by steve8708** [comment]
Fixed the filtering issues - you should now be able to properly select an option and see matching results as expected for targeting. Deployed to `beta.builder.io`, will go to production in our next push. 

Selecting multiple for queries isn't currently support but happy to make a new issue for that as a feature request
