### ISSUE TITLE
Does @builder.io/gatsby work with Gatsby 3?

### ISSUE THREAD

**Issue by rramphal** [BuilderIO/builder#451]
I was having issues loading the API key on my Gatsby 3 codebase and the I noticed the following warning:

```
Plugin @builder.io/gatsby is not compatible with your gatsby version
3.0.4 - It requires gatsby@^2.0.15
```

Does the version just need to be updated in `package.json`, or is the functionality actually broken with Gatsby 3?

**Comment by Dkendal** [comment]
Hey @rramphal! `@builder.io/gatsby` does work with Gatsby 3 - thanks for letting us know that the package needed to be updated to reflect this :smile:.

If you install the latest version of this package (2.0.4) you should no longer receive the warning.

```bash
npm install --save @builder.io/gatsby@latest
```

Let me know if you encounter other issues like this, thanks!
