### ISSUE TITLE
Unable to install using  :  npm install @builder.io/angular

### ISSUE THREAD

**Issue by rekita-udchalo** [BuilderIO/builder#461]
+ npm install @builder.io/angular
+             ~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@builder' can be used only as an argument to a      
command. To reference variables in an expression use '$builder'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

Getting the above error.

**Comment by steve8708** [comment]
hey @rekita-udchalo - for powershell try putting a single quote around the package name

```
npm install '@builder.io/angular'
```

more info here https://stackoverflow.com/a/55183851

**Comment by carlosviniciusananias** [comment]
> ei @rekita-udchalo - para powershell, tente colocar uma aspa simples no nome do pacote
> 
> ```
> npm install '@builder.io/angular'
> ```
> 
> mais informações aqui https://stackoverflow.com/a/55183851

this worked fine for me. thank you!
