### ISSUE TITLE
Builder SDK - servers hang up until we restarted

### ISSUE THREAD

**Issue by XianfuZhengAfterpay** [BuilderIO/builder#484]
### What happened
During the incident, all page requests were timeout except for those pages cached by cloudflare. See below sceenshot.
![image](https://user-images.githubusercontent.com/61843506/120733488-9f7d0100-c52a-11eb-8386-4360ec0f6e5a.png)

### Our investigations and findings

- There was a build in progress which will call Builder API to get page content but never ends. We killed from heroku command line. The incident happens ~10 minutes of start of the build

![image](https://user-images.githubusercontent.com/61843506/120733806-292cce80-c52b-11eb-9b36-9d85b2838b9f.png)
- Dyno memory usage looks normal

![image](https://user-images.githubusercontent.com/61843506/120733923-5ed1b780-c52b-11eb-9923-72ee01a7d544.png)
- There wasn't traffic spikes
![image](https://user-images.githubusercontent.com/61843506/120733981-77da6880-c52b-11eb-956c-c1fb37c1e629.png)

- Calls to Builder API looks normal
![image](https://user-images.githubusercontent.com/61843506/120734148-c38d1200-c52b-11eb-9f4b-9da9fad99a93.png)

**Comment by XianfuZhengAfterpay** [comment]
Thanks Guangyu .

One more thing I noticed, is the request number to builder API gradually
decreased.

**Comment by steve8708** [comment]
thanks @gydongAP and @XianfuZhengAfterpay - this is helpful

the next thing we need to try and do is isolate what happened here. shy of having full access to your code and understanding how different states are handled, I am wondering if there is a way we can isolate a potential problem in the SDK

shy of seeing your code directly and knowing the nuances of how your stack handles certain situations I'm having trouble thinking of how to reproduce these findings in isolation - would it be possible for you to try and take a stab at this?

**Comment by XianfuZhengAfterpay** [comment]
+ Shahar

@Shahar Sharon ***@***.***>  since you are more
familiar with the code base, do you mind providing some insights here?
