### ISSUE TITLE
[Builder.io] Can not delete users from organization

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#49]
When I trying to delete user from organization ( https://builder.io/account/organization ) I getting 404 with this error:
![image](https://user-images.githubusercontent.com/22659410/73097219-edb9d300-3ee6-11ea-8177-a6e005bec7ab.png)

Also before I got this error I got an information (toastr) that said "Done" but even after refresh user is still on the list.

**Comment by ca136** [comment]
This should now be resolved
