### ISSUE TITLE
"Get generated code" doesn't seem to output working code

### ISSUE THREAD

**Issue by nsangwan** [BuilderIO/builder#497]
I created a form and generated its code for React.

The generated code seems to expect `@builder.io/react` components like - `FormForm`, `FormInput`, `FormLabel`, `FormTextArea`, `FormSubmitButton`.  Is that correct?

If yes.

Issue 1:
These components are not imported in the generated code.

Issue 2:
Some of these components seemed to be aliased - e.g. `FormForm` from `Form`, `FormTextArea` from `TextArea` which makes it even harder to map them to actual components.

**Comment by steve8708** [comment]
hey @nsangwan - looks like you caught that we haven't implemented our form components into the compiler yet! Thanks for the reminder, will leave this ticket open to remind us to get to this :)

**Comment by nsangwan** [comment]
@steve8708 thanks for acknowledging. Planning to implement anytime in foreseeable future?

**Comment by steve8708** [comment]
absolutely, hopefully in the next few weeks. and in the meantime you can generally just swap out the components to the last part of their name, lowercased, e.g. by hand:

<FormForm> -> <form>
<FormInput> -> <input>
<FormLabel> -> <label>

etc

You can see the full implementations over [here](https://github.com/BuilderIO/builder/tree/master/packages/react/src/blocks/forms). They are all quite simple, e.g. [Button is here](https://github.com/BuilderIO/builder/tree/master/packages/react/src/blocks/forms)
