### ISSUE TITLE
Builder editor occasionally doesn't load

### ISSUE THREAD

**Issue by ca136** [BuilderIO/builder#50]
The content editor page returns the message:
> Oh no! We had an error :( Try refreshing this page and chat us or contact help@builder.io if this continue

**Comment by ca136** [comment]
@JacoboGallardo I'm having some trouble reproducing this, can you let me know if your team is still seeing this issue? If so, do you have any more information on steps to reproduce? Thanks!

**Comment by JacoboGallardo** [comment]
Sure, I will ask the user if this is happening on long-lived sessions. Anything else we should gather before coming back to you? Should we reload the page and capture the console output in the browser?

**Comment by ca136** [comment]
This may have been fixed with one of our recent releases. Going to close, and will re-open if it's still happening.
