### ISSUE TITLE
Limited display and functionality when using RenderContent vue component

### ISSUE THREAD

**Issue by joroe** [BuilderIO/builder#522]
I am trying to include builder pages in a vue/nuxt project. When I use the RenderContent I get prerendered HTML with limited display (I guess because of missing lazy loading) and functionality (drawer toggles, carousel). When using the builder-component webcomponent I can see that it gets the page with prerender false and renders the components as expected. Can you please shed some light whats up with that? Is that intended? Incomplete? A bug? I would expect the same behavior from RenderContent in the vue package. Thanks for clarification!

**Comment by teleaziz** [comment]
Hi @joroe , thanks for reporting this, you were running into a bug that affected interactivity of builder content rendered by the vue sdk, a fix has been merged and released on the `dev` channel:
if you'd like to get the fix in your codebase:
```
npm install @builder.io/vue@dev
```

We will also do a patch release next, keeping this issue open until then.

**Comment by teleaziz** [comment]
This has been fixed and released in `@buider.io/vue@0.1.11`
