### ISSUE TITLE
Feature Request: Support for multiple, custom breakpoints

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#53]
Severity: 3 of 5

Builder currently supports 3 breakpoints. Our site uses the standard Bootstrap breakpoints which include 5, XL, L, M, S, XS https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints

We'd love it if Builder supported all 5 with the ability to customize the pixel widths at the Organization or Model level.

**Comment by steve8708** [comment]
Thanks @JefferyReidKnowde 

Due to technical constraints adding a 4th breakpoints and the ability to customize the width value for each should be feasible and get you much closer to what you are looking for

Will keep here in our backlog for now with that scope

**Comment by JefferyReidKnowde** [comment]
Any update on this? We'd love to get this ASAP
