### ISSUE TITLE
Webcomponents error while using Edge

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#55]
Whenever we are trying to access our page using Edge we are getting error in console.

![webcomponents-wrror](https://user-images.githubusercontent.com/22659410/73665762-ef7f5580-46a1-11ea-8a41-676e1c2d62c5.png)

**Comment by ca136** [comment]
It's actually coming from the `@webcomponent/custom-element` polyfill, which isn't needed in Edge so we should remove. Is this preventing content from displaying or is it just a warning? FWIW I can see content on Edge, just want to make sure nothing else is broken.

**Comment by ca136** [comment]
Not seeing this anymore so going to close, please let me know if you're still having this issue @lyczos
