### ISSUE TITLE
builder.get field type file returns invalid url

### ISSUE THREAD

**Issue by jaketigbd** [BuilderIO/builder#559]
I have a model that requires a file

![image](https://user-images.githubusercontent.com/49957778/133115351-cfe721d7-0efe-4ee6-a4a6-01f5234639bc.png)

When I retrieve the model the image url is not encoded properly

`await builder.get('model-name', {options}).toPromise()`

returns 

```
{
  image: 'https://cdn.builder.io/api/v1/image/assets%2F12cbceb6<redacted>%2F16faa<redacted>',
  ...
}
```

Part of the URL appears to be URL encoded. I would expect this return `/` instead of `%2F`

I am currently handling this with `image.replace(/%2F/g, '/')`

**Comment by steve8708** [comment]
hey @jaketigbd - that encoding is actually intentional, does the URL not work without it? can you share the full original URL?

**Comment by jaketigbd** [comment]
@steve8708 - it doesn't seem to, at least when using next/image 

next/image converts it to this URL: `http://localhost:3000/_next/image?url=https%3A%2F%2Fcdn.builder.io%2Fapi%2Fv1%2Fimage%2Fassets%252F12cbceb6be9648e2a8a23b8c10684f0b%252F16faa65eb387409db12463472119ec2a&w=1920&q=75`

When I URL decode this it appears to attempt to fetch `https://cdn.builder.io/api/v1/image/assets%2F12cbceb6be9648e2a8a23b8c10684f0b%2F16faa65eb387409db12463472119ec2a&w=1920&q=75`

which returns `{"status":404,"message":"Image not found"}` when I try to open it in chrome.

I'm left with a broken image

![image](https://user-images.githubusercontent.com/49957778/133141944-30bd631d-9c85-44b3-a4ba-62f8160b0d95.png)

using `.replace(/%2F/g, '/')` solves this so if this is intentional I'm fine with that.

**Comment by jaketigbd** [comment]
Ah I see. This is caused by the parameters added from next/image 
The URL returned works fine without `&w=1920&q=75`

Apologies for the confusion.

**Comment by steve8708** [comment]
great to know, thanks for the useful writeup and updates @jaketigbd ! interesting that next.js adds `&` instead of `?`, if you can force it to use `?w=x&q=x` instead of `&w=x&q=x` then that'll work as desired as well
