### ISSUE TITLE
Register Components with Vue/Nuxt

### ISSUE THREAD

**Issue by IonutRealDevs** [BuilderIO/builder#565]
Is possible to register components with Vue/Nuxt? If yes how?
I found out how to do it using Next but i can't find anything about Vue or Nuxt.
Thank you.

**Comment by steve8708** [comment]
hey @IonutRealDevs - we have a beta of our v2 Vue SDK that supports this - you can check it out over here and would value your feedback and reporting any issues you hit with it https://github.com/BuilderIO/builder/tree/main/examples/vue-nuxt

**Comment by IonutRealDevs** [comment]
Thank you i'll check it out
