### ISSUE TITLE
Homepage is not displaying on IE11 - wrong userAttributes

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#59]
Whenever we are trying to display any content on IE11 on home page we are getting an empty response.
It is because of wrong user attribute URL Path:

On Chrome etc. builder is passing:
`userAttributes.urlPath: '/'`

but on IE11 builder passing empty string:
`userAttributes.urlPath: ''`

**Comment by ca136** [comment]
@lyczos I'm hoping this is fixed in: @builder.io/angular@1.0.83-alpha.6
