### ISSUE TITLE
Generated React code in model options renders wrong 

### ISSUE THREAD

**Issue by exocode** [BuilderIO/builder#595]
```jsx
const const MyComponent = () => (
  <BuilderComponent
    model="header-bar" />
)
```
With the code generated I get 
`'const' is not allowed as a variable declaration name.ts(1389)`

shouldn't it be a bit different like: 

```jsx
const TopBarComponent = () => {
return (
  <BuilderComponent model="header-bar"/>)
}

export default TopBarComponent
```

or 

```jsx
const TopBarComponent = () => <BuilderComponent model="header-bar"/>

export default TopBarComponent
```

![Bildschirmfoto 2021-10-11 um 19 34 27](https://user-images.githubusercontent.com/1597621/136831726-9c587625-5958-47e4-9859-9657b5f09b16.png)

**Comment by steve8708** [comment]
ah, thanks @exocode ! the intention was `export const`, will fix this now
