### ISSUE TITLE
Add `renderImage` to `BuilderComponent`

### ISSUE THREAD

**Issue by kevva** [BuilderIO/builder#617]
Like `renderLink`, I think `renderImage` would be a useful addition as well, especially if you're using Next.js which comes with [image optimization](https://nextjs.org/docs/basic-features/image-optimization).

**Comment by steve8708** [comment]
hey @kevva - the way to do this is to override the built-in image component. The reason `renderLink` doesn't work this way is we don't have a `Link` component, instead any block can be linked so it needs the separate flavor

But for images you will want to just do

```tsx
function MyImage(props) { ... }

Builder.registerComponent(MyImage, {
  name: 'Image', // This name is what overrides the built in component named "Image"
  inputs: [...]
})
```
