### ISSUE TITLE
plugin-contentful Contentful Error

### ISSUE THREAD

**Issue by codercatdev** [BuilderIO/builder#630]
This might hold true for all of the plugins, but the user should receive an error similar to what is coming from the console.

Currently I get a spinning popup with a bad API call.
![image](https://user-images.githubusercontent.com/3102249/142222593-8eb5ab52-0865-4ad4-bee6-ee4136c13100.png)

Here is the information in the console.
![image](https://user-images.githubusercontent.com/3102249/142222543-40249311-2df8-4270-a1dc-a05965d581f8.png)

**Comment by azhrzafar** [comment]
Probably you are using the access token of an environment other than `master`. In the plugin, it is hardcoded as `master` for environment https://github.com/teleaziz/builder/blob/9d8825f8501303464a1fe96e36aa7ddffb6e76e8/plugins/contentful/src/plugin.ts#L99-L105
