### ISSUE TITLE
Package support

### ISSUE THREAD

**Issue by bsbechtel** [BuilderIO/builder#642]
Hello,

Is this package still being maintained? Looks like the last commit was in June of this year. Considering Builder is a relatively new product, I would expect more active work on this package as a part of that effort.

Thanks

**Comment by steve8708** [comment]
He @bsbechtel - our last commit was [6 days ago](https://github.com/BuilderIO/builder/commits/main), where do you see the last one was in June:

**Comment by bsbechtel** [comment]
Sorry, I didn't realize I was inside the Angular package when I was looking at it. Looks like that package hasn't been updated in a few months. Angular is now on v13.

**Comment by steve8708** [comment]
ah yes, generally speaking angular updates don't require our SDK to update every time. though if there are any incompatibilities don't hesitate to file issues and we're happy to look into them

**Comment by bsbechtel** [comment]
Ok sounds good. Thank you for looking into it quickly....I had a chance to explore things the other day, and it all looks very promising!
