### ISSUE TITLE
Missing registration for Core:***

### ISSUE THREAD

**Issue by IslamRustamov1** [BuilderIO/builder#648]
Hello,

After updating **@builder.io/react** from **1.1.46** to **1.1.47** I started getting a message in the console:
`Missing registration for Core:Product price, have you included the registration in your bundle?`

What is `Core:Product price`?
 Is it a symbol?
 How can I fix this message?

**Comment by teleaziz** [comment]
This warning shows when using a custom component on a Builder content that's no longer registered for some reason, have you imported the registration for this component?

**Comment by teleaziz** [comment]
How can you fix? 

- Check if this is a custom component in your codebase that's no longer imported or registered.

- If that's intentional and you no longer wish to use that custom component, go to your content and search in the layers tab for it, and remove that layer

**Comment by IslamRustamov1** [comment]
thanks, the problem was in the test component
