### ISSUE TITLE
SSR should send model option defaults when not set

### ISSUE THREAD

**Issue by fasaas** [BuilderIO/builder#65]
When using NextJS to do SSR, after executing the following code 
```js
  static async getInitialProps(ctx) {
    const { res, req } = ctx;
    const page = await builder.get(builderModel, { req, res }).promise();
    return { ...initialProps, page };
  }
```
Could it be possible to return the model option defaults even when not set?

**Comment by steve8708** [comment]
fixed and released to production :) 

couple notes -

- default values weren't being set on client or server (aka they weren't on the data at all) - this is now fixed such that when creating a new content entry all default values are set to the `data` object
- this isn't backwards compatible, will only apply to new content created

thanks for reporting @fasaas !
