### ISSUE TITLE
App renders within itself on debug

### ISSUE THREAD

**Issue by HeavenlyEntity** [BuilderIO/builder#663]
### Bug With App Rendering While in debug

Hey Builder.io team! I have found an interesting bug which I have encountered debugging my test store. You can simply recreate this bug while hitting F12 in the page builder on a store that is not connecting correctly and try to select a product then size the tool window a little bigger on the screen to see the network requests. 

![image](https://user-images.githubusercontent.com/39228141/145748798-c53b4422-fa1c-4315-bd6a-9dd485523fae.png)

Very interesting. I have a few more bugs I have found too but some I know are already in as issues. I'll post more during my testing.

**Comment by teleaziz** [comment]
Hi @HeavenlyEntity thanks for reporting, can you please provide your public api key, it'll help with investigating the source of this issue
