### ISSUE TITLE
Builder.io editor mode preview do not match normal mode 

### ISSUE THREAD

**Issue by lyczos** [BuilderIO/builder#67]
When we are trying to wrap our symbol in one row, on editor it is working fine but normal mode creating some wrapper that's preventing form applying correct styles.

Screeen recording:
https://www.loom.com/share/ab99e7c50fcd4a23b0487fab0a649b2e
Builder.io:
https://builder.io/content/149b6635affa46ec9a6a0233f825e040

**Comment by steve8708** [comment]
hey @lyczos - trying to reproduce but it looks like the preview URL was removed for this model so can't see the preview / live comparison

Also looks like the content has updated there too (and the current content looks the same when previewing vs editing) - any latest tips you can give to reproduce would be much appreciated!

**Comment by teleaziz** [comment]
Hi @lyczos, any updates on this?

**Comment by ca136** [comment]
@lyczos going to close for now, but please let us know if this is still an issue!
