### ISSUE TITLE
Getting a warning regarding trying to call setState before component is mounted

### ISSUE THREAD

**Issue by tedlin182** [BuilderIO/builder#8]
#### Issue

I just updated the version of `@builder/react` locally and when I'm trying to test the 404 page, I'm now getting this warning.

![Screen Shot 2019-11-19 at 4 04 10 PM](https://user-images.githubusercontent.com/290272/69257849-9444c900-0b70-11ea-98f1-412bfc53a13a.png)

Our 404 page doesn't load either now and just renders the `Loading...` copy. This warning also pops up on our test Builder page also along with a warning regarding `class` instead of `className`

![Screen Shot 2019-11-19 at 4 05 47 PM](https://user-images.githubusercontent.com/290272/69258480-83488780-0b71-11ea-8be4-ae1229f02a3a.png)

The test page renders fine however. Will continue seeing if it's something our end, but can't seem to find anything different as it was working as of Nov. 15th.

#### Setup

Used the example in the docs <https://github.com/BuilderIO/builder#dynamic-landing-pages>

**Comment by steve8708** [comment]
Hey Ted! Thanks for the report. Can you try two things for me?

1) Install the latest dev version of the react package `npm install --save @builder.io/react@dev`
2) Change the name of the `onContentLoad` prop in `<BuilderComponent />` to `contentLoaded={...}` (my mistake in latest docs!)

These appear to work for me (can try it out [here](https://codesandbox.io/s/github/BuilderIO/builder/tree/master/examples/react)). If this doesn't work for you could you modify that [codesandbox entry](https://codesandbox.io/s/github/BuilderIO/builder/tree/master/examples/react) to see if you can make the code more like yours and reproduce your issue and send me the reproduced example?

Thanks!

**Comment by tedlin182** [comment]
> 2\. contentLoaded

Thanks @steve8708 ! It worked!

**Comment by steve8708** [comment]
Great! My apologies for the typo and let me know if I can help with anything else!
