### ISSUE TITLE
Gatsby Example: No builder-config

### ISSUE THREAD

**Issue by danielmaartens-sovtech** [BuilderIO/builder#84]
@steve8708 

I am struggling to get the Gatsby Example running - i.e. `builder/examples/gatsby`.

Following the instructions of the readme `npm run dev` results in an error indicating that `builder-config` required on line 1 of gatsby-config.js does not exist.

Are there any other steps I am supposed to follow to get this example up and running that are not documented in the readme ?

**Comment by steve8708** [comment]
Sorry to hear that @danielmaartens-sovtech - we made an update to the example to use our new plugin and must have missed a file 

Well get this fixed first thing Monday, and you can see the recent change that removes that file here 

https://github.com/BuilderIO/builder/commit/34d1dd441691806f08e66b9cc38cff302e085ca9

Using the version before this update should work as expected, or pulling in the missing file yourself from there should help you out, and if this isn't urgent well have this example updated Monday

**Comment by danielmaartens-sovtech** [comment]
@steve8708 

Thanks for your response.

I noticed that the `getGQLOptions` function that you import from the missing `builder-config.js` file is not used in the `gatsby-config.js`. Its use was removed in the same commit you referenced above. 

Is this also a mistake ? 

If not, how does the graphql connection get set up ?

**Comment by steve8708** [comment]
@danielmaartens-sovtech try taking a look here for the [fix](https://github.com/BuilderIO/builder/pull/86) - will get merged soon but think this should answer your questions above in the meantime!

**Comment by steve8708** [comment]
Ok, fix is merged! Please reopen if you have any further issues here though, and thanks for reporting @danielmaartens-sovtech
