### ISSUE TITLE
How to get author name via Content API?

### ISSUE THREAD

**Issue by danhav** [BuilderIO/builder#841]
hey guys, I'd like to get author name via Content API.

After hitting https://cdn.builder.io/api/v2/content/page?apiKey=...
I receive default page response with fields like lastUpdatedBy and createdBy but they seem to be encrypted.

Does anyone know how decrypt those fields or get author name in some other way?

**Comment by samijaber** [comment]
@danhav Closing this as I've seen you asked in the forum and received an answer there!
