### ISSUE TITLE
Invalid DOM properties

### ISSUE THREAD

**Issue by danielmaartens-sovtech** [BuilderIO/builder#87]
@steve8708 

Hi Steve

I've come across this error:

`Warning: Invalid DOM property "class". Did you mean "className"?`

![image](https://user-images.githubusercontent.com/59686723/75752248-02348b00-5d31-11ea-8103-bc19aead8ac5.png)

Am I missing an extra step here or is this a kind of red-herring error that I can ignore ?

Also custom javascript for elements is completely ignored.

**Comment by steve8708** [comment]
Thanks for reporting @danielmaartens-sovtech 

In short - you can ignore :) It shows up in development only and is benign (doesn't affect any functionality)

Slightly longer answer - just pushed a fix to remove this error that will be published to the SDKs shortly 👍
