### ISSUE TITLE
href not added to a tag for text elements with link URL

### ISSUE THREAD

**Issue by danielmaartens-sovtech** [BuilderIO/builder#88]
@steve8708 

In my design I have this:

![image](https://user-images.githubusercontent.com/59686723/75754188-f054e700-5d34-11ea-8738-8cac75b6b947.png)

But in the preview I have this:

![image](https://user-images.githubusercontent.com/59686723/75754165-e4692500-5d34-11ea-9022-2e6757731f75.png)

`href` with link not added. 

I have to create a new button element, copy the style and set the URL in order for the link to work.

Any reason why this functionality is not working as expected ?

**Comment by steve8708** [comment]
Hey @danielmaartens-sovtech - thanks for reporting, that's odd - can you link me to the content you are editing so I can look in the backend? e.g. builder.io/content/...

**Comment by ca136** [comment]
@danielmaartens-sovtech are you still seeing this issue? We haven't been able to reproduce on our end.

**Comment by ca136** [comment]
Going to close, but please let us know if you see this again and we'll investigate.
