### ISSUE TITLE
Builder page content not rendering everything

### ISSUE THREAD

**Issue by tedlin182** [BuilderIO/builder#9]
#### Issue

This is in the `@builder.io/react@dev` build. It looks like now the Builder page on our site is not rendering everything that's published in the dashboard page

**In Builder**

![Screen Shot 2019-11-21 at 8 59 42 AM](https://user-images.githubusercontent.com/290272/69359371-519cf280-0c3d-11ea-809d-5d2b3f406c3b.png)

**Our site (running locally)**

![Screen Shot 2019-11-21 at 9 00 12 AM](https://user-images.githubusercontent.com/290272/69359411-65e0ef80-0c3d-11ea-9464-e4089d05b449.png)

It seems like it was working fine for a little bit, but not sure if you pushed any updates to the dev build that might be causing this.

**Comment by steve8708** [comment]
ah interesting - Builder on your site on the dev branch isn't finding the Builder components (button, columns, etc)

there are two small changes to how this is handled in the latest alpha releases, but they are working ok for others on them. so I can try and reproduce can you send me your full package.json file contents? (or at least just the dependencies section)

**Comment by steve8708** [comment]
as a side note - this is on the latest version of the alpha too https://codesandbox.io/s/github/BuilderIO/builder/tree/master/examples/react so hoping something in your package.json (or maybe if you have any other ideas) can help us reproduce what you are seeing there too. it's also possible the latest alpha version fixes but a prior one had the issue so also worth trying out `1.0.98-alpha.9` like in that example in case you're on an earlier alpha that perhaps had a temp issue

**Comment by tedlin182** [comment]
@steve8708 Here's our package list. We also have dev dependencies and run off a CRA base.

Let me know if you need more info though

```
"dependencies": {
    "@builder.io/react": "^1.0.98-alpha.9",
    "@contentful/rich-text-html-renderer": "^13.4.0",
    "@sentry/browser": "^5.7.1",
    "@storybook/addon-backgrounds": "^5.2.5",
    "@storybook/addon-centered": "^5.2.5",
    "apisauce": "^1.0.2",
    "classnames": "^2.2.6",
    "connected-react-router": "^6.3.1",
    "contentful": "^7.9.1",
    "history": "^4.9.0",
    "lodash": "^4.17.11",
    "node-sass": "^4.11.0",
    "query-string": "^6.2.0",
    "ramda": "^0.26.1",
    "react": "^16.8.2",
    "react-content-loader": "^4.2.2",
    "react-dom": "^16.8.2",
    "react-fontawesome": "^1.6.1",
    "react-helmet": "^5.2.0",
    "react-imgix": "^8.6.4",
    "react-keshan-carousel": "^1.10.9",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-router-hash-link": "^1.2.2",
    "react-scripts": "3.0.1",
    "react-scroll": "^1.7.14",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-persist-transform-filter": "0.0.18",
    "redux-saga": "^1.0.5",
    "redux-thunk": "^2.3.0",
    "sanitize-html": "^1.20.1",
    "seamless-immutable": "^7.1.4",
    "shopify-buy": "^2.8.1"
  },
```

**Comment by steve8708** [comment]
Great, thanks Ted

Sadly I updated the codesandbox with your exact dependencies and can't reproduce https://codesandbox.io/s/builderioexample-react-2hpkp

Can you send me two more things to attempt to reproduce - your devDependencies and the full contacts of your package-lock.json (or yarn.lock if you use that)

Also possibly worth trying on your end - wiping out your node_modules and reinstalling - but happy to copy your package-lock.json to a sandbox to see if I can reproduce first so we can avoid you needing to do that

**Comment by tedlin182** [comment]
@steve8708 Yeah I wiped out the `package-lock.json` and the `node_modules` and reinstalled and still having that issue.


Here's our `package.json` though:

```
{
  "name": "answered-falcon",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@builder.io/react": "^1.0.98-alpha.9",
    "@contentful/rich-text-html-renderer": "^13.4.0",
    "@sentry/browser": "^5.7.1",
    "@storybook/addon-backgrounds": "^5.2.5",
    "@storybook/addon-centered": "^5.2.5",
    "apisauce": "^1.0.2",
    "classnames": "^2.2.6",
    "connected-react-router": "^6.3.1",
    "contentful": "^7.9.1",
    "history": "^4.9.0",
    "lodash": "^4.17.11",
    "node-sass": "^4.11.0",
    "query-string": "^6.2.0",
    "ramda": "^0.26.1",
    "react": "^16.8.2",
    "react-content-loader": "^4.2.2",
    "react-dom": "^16.8.2",
    "react-fontawesome": "^1.6.1",
    "react-helmet": "^5.2.0",
    "react-imgix": "^8.6.4",
    "react-keshan-carousel": "^1.10.9",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-router-hash-link": "^1.2.2",
    "react-scripts": "3.0.1",
    "react-scroll": "^1.7.14",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-persist-transform-filter": "0.0.18",
    "redux-saga": "^1.0.5",
    "redux-thunk": "^2.3.0",
    "sanitize-html": "^1.20.1",
    "seamless-immutable": "^7.1.4",
    "shopify-buy": "^2.8.1"
  },
  "scripts": {
    "analyze:js": "source-map-explorer 'build/static/js/*.js'",
    "analyze:css": "source-map-explorer 'build/static/css/*.css'",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "serve": "serve -s build",
    "build:serve": "run-s build serve",
    "cypress:dev": "cypress open",
    "cypress:build": "CYPRESS_baseUrl=http://localhost:5000 run-p build:serve cypress:dev",
    "lint": "node_modules/eslint/bin/eslint.js ./src",
    "lint-fix": "node_modules/eslint/bin/eslint.js ./src --fix",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public",
    "gradle-build-qa": "gradle restoreConfig -Ptarget=qa",
    "gradle-build-prod": "gradle restoreConfig -Ptarget=prod",
    "surge": "npm run build && mv build/index.html build/200.html && surge build"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@storybook/addon-actions": "^5.2.5",
    "@storybook/addon-knobs": "^5.2.5",
    "@storybook/addons": "^5.2.5",
    "@storybook/react": "^5.2.5",
    "babel-loader": "^8.0.5",
    "cypress": "^3.2.0",
    "eslint-plugin-cypress": "^2.2.1",
    "jest-dom": "^3.1.3",
    "npm-run-all": "^4.1.5",
    "react-testing-library": "^6.0.0",
    "redux-devtools-extension": "^2.13.8",
    "serve": "^10.1.2",
    "source-map-explorer": "^2.0.1",
    "storybook-addon-jsx": "^7.1.6"
  }
}
```

I can see the text components coming back in the `content` within `contentLoaded`:

![Screen Shot 2019-11-21 at 2 40 50 PM](https://user-images.githubusercontent.com/290272/69382862-f4209a00-0c6c-11ea-8799-61333ed61fd0.png)

**Comment by steve8708** [comment]
Great, thanks Ted. Yeah, this missing part is for some reason when rendering the components not being found which is very odd.

Can you send me your package-lock.json or yarn.lock as well?

**Comment by tedlin182** [comment]
@steve8708 Sure, i'll email it to you

**Comment by steve8708** [comment]
Ok! Was able to reproduce and verify the fix - try out `@builder.io/react@1.0.98-alpha.10`

**Comment by tedlin182** [comment]
@steve8708 Awesome, it works. Thanks for fixing that!

**Comment by steve8708** [comment]
Great, anytime!
